'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5477
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''kameitenkihon_jyusho_user クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class kameitenkihon_jyusho_user

    '''<summary>
    '''titleText5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents titleText5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''titleInfobar5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents titleInfobar5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTouroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''meisaiTbody5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents meisaiTbody5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxAddNengetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxAddNengetu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxYuubinNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxYuubinNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKensaku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxJyuusyo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTodoufuken コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlTodoufuken As Global.Itis.Earth.WebUI.common_drop

    '''<summary>
    '''tbxJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxJyuusyo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxBusyoMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxBusyoMei1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxDaihyousyaMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxDaihyousyaMei1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTelNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTelNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxFaxNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxFaxNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxMailAddress コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxMailAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxBikou11 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxBikou11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxBikou21 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxBikou21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hidUpdTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidUpdTime As Global.System.Web.UI.WebControls.HiddenField
End Class
