'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''HannyouSiireSyuusei クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class HannyouSiireSyuusei

    '''<summary>
    '''Head1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUniqueNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUniqueNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenGamenMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSesyuFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSesyuFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenOpenValues コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenOpenValues As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SpanTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonClose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonClose As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonUpdate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonUpdate As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanelSyouhinInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhinInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextHanSiireNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHanSiireNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckTorikesi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanelSyouhin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhin As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhinCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenSyouhinCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinCdOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyouhinSearchType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinSearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTargetId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTargetId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenZeiritu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiritu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonSearchSyouhin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchSyouhin As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextSyouhinMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhinMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SpanSiireSyoriZumi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSiireSyoriZumi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanelKameiten コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelKameiten As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSearchKameiten コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchKameiten As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextKameitenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenKameitenSearchType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenSearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKamentenCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKamentenCdOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''UpdatePanel_KameiToikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel_KameiToikesi As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTorikesiRiyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTorikesiRiyuu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanelTysKaisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelTysKaisya As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTysKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTysKaisyaCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSearchTysKaisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchTysKaisya As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextTysKaisyaMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTysKaisyaMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTysKaisyaCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaCdOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKamentenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKamentenCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTysKaisyaSearchType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaSearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextTanka コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTanka As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSuu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectZeiKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectZeiKbn As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanZeiKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanZeiKbn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextUriGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyouhiZeiGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhiZeiGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSiireDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSiireDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDenpyouSiireDateDisplay コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireDateDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanelDenpyouSiireDateSyuusei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelDenpyouSiireDateSyuusei As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextDenpyouSiireDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKubun As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextHosyousyoNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHosyousyoNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBangou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonSesyumeiSyutoku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSesyumeiSyutoku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanelSesyumei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSesyumei As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextSesyumei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSesyumei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAreaTekiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAreaTekiyou As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
