'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3625
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''IraiStep2 クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class IraiStep2

    '''<summary>
    '''gamenId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents gamenId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenAjaxFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenAjaxFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''IraiCtrl1_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IraiCtrl1_1 As Global.Itis.Earth.WebUI.IraiCtrl1

    '''<summary>
    '''IraiCtrl2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IraiCtrl2_1 As Global.Itis.Earth.WebUI.IraiCtrl2

    '''<summary>
    '''irai2_next コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai2_next As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''irai2_next_before コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai2_next_before As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanelStep2RegBtn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelStep2RegBtn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''irai2_exeDirectTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai2_exeDirectTouroku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''irai2_exeDirectTouroku_exe コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai2_exeDirectTouroku_exe As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
