'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3625
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''PopupGamenKidou クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class PopupGamenKidou

    '''<summary>
    '''Head1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''AjaxScriptManager1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AjaxScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''SpanPopupMess1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanPopupMess1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SelectKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectKubun As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanKubun As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ButtonCheckIsJibanData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonCheckIsJibanData As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanel_BukkenKidou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel_BukkenKidou As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HiddenIsJibanData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenIsJibanData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenIsJibanDataOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenIsJibanDataOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonJutyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonJutyuu As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncJutyuuOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncJutyuuOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonHoukokusyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHoukokusyo As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncHoukokusyoOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncHoukokusyoOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonKairyouKouji コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKairyouKouji As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncKairyouKoujiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncKairyouKoujiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonHosyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHosyou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncHosyouOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncHosyouOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonTeibetuSyuusei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTeibetuSyuusei As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncTeibetuSyuuseiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncTeibetuSyuuseiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonTeibetuNyuukinSyuusei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTeibetuNyuukinSyuusei As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncTeibetuNyuukinSyuuseiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncTeibetuNyuukinSyuuseiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonPopupBukkenRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonPopupBukkenRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncButtonPopupBukkenRirekiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncButtonPopupBukkenRirekiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonPopupTokubetuTaiou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonPopupTokubetuTaiou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncButtonPopupTokubetuTaiouOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncButtonPopupTokubetuTaiouOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonSearchMousikomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchMousikomi As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncButtonSearchMousikomiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncButtonSearchMousikomiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ButtonSearchFcMousikomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchFcMousikomi As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''AncButtonSearchFcMousikomiOW コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents AncButtonSearchFcMousikomiOW As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
