'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''PopupBukkenRirekiSyuusei クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class PopupBukkenRirekiSyuusei

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenNyuuryokuNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenNyuuryokuNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenGamenMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''divSelect コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divSelect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SelectTmpCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectTmpCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonClose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonClose As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonUpdate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonUpdate As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBangou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSesyuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSesyuMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyubetu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyubetu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyubetu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBunrui コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunrui As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextHizuke コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHizuke As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextHanyouCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHanyouCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAreaNaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAreaNaiyou As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextTourokuSya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTourokuSya As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextTourokuDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTourokuDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKousinSya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKousinSya As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKousinDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKousinDate As Global.System.Web.UI.WebControls.TextBox
End Class
