'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3625
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''SearchHannyouSiire クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class SearchHannyouSiire

    '''<summary>
    '''ButtonSinki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSinki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''BtnCsvInput コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents BtnCsvInput As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanel_syouhin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel_syouhin As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhinCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnSyouhinSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSyouhinSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextHinmei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHinmei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hdnSyouhinType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnSyouhinType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextAddDateFrom コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAddDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextAddDateTo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAddDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''UpdatePanel_TysKaisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel_TysKaisya As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTysKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTysKaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ButtonTysKaisyaSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTysKaisyaSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextTysKaisyaMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTysKaisyaMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextTysKaisyaMeiKana コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTysKaisyaMeiKana As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextSiireDateFrom コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSiireDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextSiireDateTo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSiireDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextDenpyouSiireDateFrom コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextDenpyouSiireDateTo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextHosyousyoNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHosyousyoNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''maxSearchCount コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents maxSearchCount As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''search コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents search As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''CheckTorikesiTaisyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckTorikesiTaisyou As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''returnTargetIds コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents returnTargetIds As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''afterEventBtnId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents afterEventBtnId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''firstSend コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents firstSend As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''search_shouhin23 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents search_shouhin23 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''resultCount コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents resultCount As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''DivLeftTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivLeftTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TableTitleTable1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TableTitleTable1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''DivRightTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivRightTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TableTitleTable2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TableTitleTable2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''DivLeftData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivLeftData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TableDataTable1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TableDataTable1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''DivRightData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DivRightData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TableDataTable2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TableDataTable2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''sendTargetWin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents sendTargetWin As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
