'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3620
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TeibetuNyuukinSyuusei クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class TeibetuNyuukinSyuusei

    '''<summary>
    '''ButtonTourokuSyuuseiJikkou1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTourokuSyuuseiJikkou1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonTourokuExe コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTourokuExe As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextSaisyuuKousinnsya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSaisyuuKousinnsya As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSaisyuuKousinNitiji コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSaisyuuKousinNitiji As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKubun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBangou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''callModalFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents callModalFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenNextNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenNextNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ButtonTokubetuTaiou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTokubetuTaiou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonBukkenRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBukkenRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonHosyousyoDB コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHosyousyoDB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextSetunusiMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSetunusiMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKameitenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonKameitenTyuuijouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKameitenTyuuijouhou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextTorikesiRiyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTorikesiRiyuu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenJyuusyo3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKeiretuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKeiretuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKeiretuMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEigyousyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextEigyousyoCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEigyousyoMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextEigyousyoMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblMeisai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tblMeisai As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TrKaiyakuHeader コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrKaiyakuHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenKeiriGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiriGyoumuKengen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrKaiyakuMeisai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrKaiyakuMeisai As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''UpdatePanelKaiyakuCheck コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelKaiyakuCheck As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''CheckboxKaiyakuHaraimodosikin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckboxKaiyakuHaraimodosikin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanelKaiyaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelKaiyaku As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextHenkinSyoriDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHenkinSyoriDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonTourokuSyuuseiJikkou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTourokuSyuuseiJikkou2 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''HiddenSyouhin2Cnt コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhin2Cnt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhin3Cnt コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhin3Cnt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhin4Cnt コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhin4Cnt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKaiyakuNashiFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKaiyakuNashiFlg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKaiyakuSyori コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKaiyakuSyori As Global.System.Web.UI.WebControls.HiddenField
End Class
