'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''BukkenRirekiRecordCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class BukkenRirekiRecordCtrl

    '''<summary>
    '''Tr1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBangou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenNyuuryokuNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenNyuuryokuNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenLoginUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenLoginUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SelectSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyubetu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyubetu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyubetu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TdCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdCode As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SpanBunrui コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanBunrui As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenBunrui コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunrui As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SpanNaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanNaiyou As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonSyuusei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSyuusei As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTorikesi As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Tr2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SpanTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanTorikesi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpanHenkouFukaFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHenkouFukaFlg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpanHizuke コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHizuke As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpanHanyouCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHanyouCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
