'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''GyoumuKyoutuuCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class GyoumuKyoutuuCtrl

    '''<summary>
    '''ScriptManagerProxy1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''irai1MainUpdatePanel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1MainUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HiddenKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKubun As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''iraiSessionKey コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents iraiSessionKey As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''actMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents actMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''updateDateTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents updateDateTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateUserId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateUserNm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateUserNm As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateDateTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateDateTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''errorData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents errorData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''kakuninOpenFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kakuninOpenFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''dateYesterday コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents dateYesterday As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaKaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaKaisyaCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaKaisyaCd1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaKaisyaCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaKaisyaCd2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaKaisyaMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaKaisyaMei As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaHouhouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaHouhouCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaHouhouMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaHouhouMei As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKoujiKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKoujiKaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKouzou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKouzou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKouzouMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKouzouMei As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTyousaGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaGaiyou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHanteiCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHanteiCd1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHanteiCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHanteiCd2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKojGaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKojGaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenTKojKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTKojKaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LinkKyoutuuInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LinkKyoutuuInfo As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''TitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenKyoutuuInfoStyle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKyoutuuInfoStyle As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonTokubetuTaiou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTokubetuTaiou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonBukkenRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBukkenRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonKousinRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKousinRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonTyosaMitumori コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTyosaMitumori As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonHosyousyoDB コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHosyousyoDB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonRJHS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonRJHS As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''kyoutuuInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kyoutuuInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKubun As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBangou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TdDataHakiSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdDataHakiSyubetu As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SelectDataHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectDataHaki As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanDataHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanDataHaki As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''changeHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents changeHaki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''SpanDataHakiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanDataHakiDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TdDataHakiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdDataHakiDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextDataHakiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDataHakiDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextSesyuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSesyuMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBukkenJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBukkenJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBukkenJyuusyo3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextAreaBikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAreaBikou As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextAreaBikou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextAreaBikou2 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextKeiyu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKeiyu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTatemonoKensa コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTatemonoKensa As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTyousaRenrakusaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaRenrakusaki As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTyousaTel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaTel As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTyousaFax コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaFax As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTyousaMiseTantousya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaMiseTantousya As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTyousaMail コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaMail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TdKameiten コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdKameiten As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKameitenCdTextOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenCdTextOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKameitenCdTextMae コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenCdTextMae As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKameitenTyuuiJikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenTyuuiJikou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonKameitenSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKameitenSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''kameitenSearchType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kameitenSearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextKameitenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTorikesiRiyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTorikesiRiyuu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonKameitenTyuuijouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKameitenTyuuijouhou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextKameitenTel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenTel As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKameitenFax コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenFax As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKameitenMail コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenMail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextBuilderNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBuilderNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ButtonBuilderCheck コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBuilderCheck As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextKeiretu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKeiretu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiretuCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextEigyousyoMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextEigyousyoMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenEigyousyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenEigyousyoCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextMitsumoriHituyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextMitsumoriHituyou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextHattyuusyoHituyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHattyuusyoHituyou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''UpdatePanelNG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelNG As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTyousaKaisyaNG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaKaisyaNG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextHanteiNG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHanteiNG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKoujiKaisyaNG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoujiKaisyaNG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextJioSakiFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJioSakiFlg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextFcTenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextFcTenMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextSyouhinKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhinKbn As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextDoujiIraiTousuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDoujiIraiTousuu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTatemonoYouto コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTatemonoYouto As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKosuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKosuu As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
