'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''IkkatuHenkouKihonRecordCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class IkkatuHenkouKihonRecordCtrl

    '''<summary>
    '''TrIkkatuHenkouRec1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrIkkatuHenkouRec1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TextKokyakuBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKokyakuBangou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''updateDateTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents updateDateTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextSesyuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSesyuMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrIkkatuHenkouRec2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrIkkatuHenkouRec2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TextBukkenJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBukkenJyuusyo3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenJyuusyo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrIkkatuHenkouRec3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrIkkatuHenkouRec3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TextBikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBikou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrIkkatuHenkouRec4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrIkkatuHenkouRec4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdTyousaKibouDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTyousaKibouDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextTyousaKibouDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaKibouDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TdTyousaKibouJikan コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdTyousaKibouJikan As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextTyousaKibouJikan コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaKibouJikan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectKeiyu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectKeiyu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanKeiyu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanKeiyu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBunjouCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBunjouCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextNayoseCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNayoseCode As Global.System.Web.UI.WebControls.TextBox
End Class
