'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3625
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''IkkatuHenkouTysSyouhin2RecordCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class IkkatuHenkouTysSyouhin2RecordCtrl

    '''<summary>
    '''TrTysSyouhin_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTysSyouhin_2_1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenKameitenCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaJigyousyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaJigyousyoCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiretuCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTorikeshi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTorikeshi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUriDateItem1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriDateItem1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenDbValue_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbValue_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgValue_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgValue_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenDbKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbKingaku_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgKingaku_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKbn_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHosyousyoNo_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHosyousyoNo_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBunruiCd_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunruiCd_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenZeiKbn_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiKbn_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUriDate_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriDate_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoKakuteiFlg_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKakuteiFlg_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoGaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoGaku_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenAutoKingakuFlg_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenAutoKingakuFlg_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenManualKingakuFlg_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenManualKingakuFlg_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBothKingakuChgFlg_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBothKingakuChgFlg_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysSeikyuuSaki_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysSeikyuuSaki_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSeikyuuSakiCd_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuSakiCd_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CheckAutoCalc_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckAutoCalc_2_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SPAN_Check_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Check_2_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKokyakuBangou_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKokyakuBangou_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenGamenHyoujiNo_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenHyoujiNo_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenRowDisplay_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenRowDisplay_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextNo_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNo_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSyouhin_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyouhin_2_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Syouhin_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Syouhin_2_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSelectSyouhin_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSelectSyouhin_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhinKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKingaku_2_1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucTokubetuTaiouToolTipCtrl_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ucTokubetuTaiouToolTipCtrl_2_1 As Global.Itis.Earth.WebUI.TokubetuTaiouToolTipCtrl

    '''<summary>
    '''TextUriageSyori_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageSyori_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKoumutenKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoumutenKingaku_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextJituSeikyuuKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJituSeikyuuKingaku_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyoudakusyoKingaku_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyoudakusyoKingaku_2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSeikyuuUmu_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSeikyuuUmu_2_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Seikyuu_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Seikyuu_2_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonAdd_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonAdd_2_1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonDelete_2_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonDelete_2_1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TrTysSyouhin_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTysSyouhin_2_2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenDbValue_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbValue_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgValue_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgValue_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenDbKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbKingaku_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgKingaku_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKbn_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHosyousyoNo_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHosyousyoNo_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBunruiCd_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunruiCd_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenZeiKbn_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiKbn_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUriDate_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriDate_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoKakuteiFlg_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKakuteiFlg_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoGaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoGaku_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenAutoKingakuFlg_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenAutoKingakuFlg_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenManualKingakuFlg_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenManualKingakuFlg_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBothKingakuChgFlg_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBothKingakuChgFlg_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysSeikyuuSaki_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysSeikyuuSaki_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSeikyuuSakiCd_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuSakiCd_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CheckAutoCalc_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckAutoCalc_2_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SPAN_Check_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Check_2_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKokyakuBangou_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKokyakuBangou_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenGamenHyoujiNo_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenHyoujiNo_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenRowDisplay_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenRowDisplay_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextNo_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNo_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSyouhin_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyouhin_2_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Syouhin_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Syouhin_2_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSelectSyouhin_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSelectSyouhin_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhinKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKingaku_2_2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucTokubetuTaiouToolTipCtrl_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ucTokubetuTaiouToolTipCtrl_2_2 As Global.Itis.Earth.WebUI.TokubetuTaiouToolTipCtrl

    '''<summary>
    '''TextUriageSyori_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageSyori_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKoumutenKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoumutenKingaku_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextJituSeikyuuKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJituSeikyuuKingaku_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyoudakusyoKingaku_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyoudakusyoKingaku_2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSeikyuuUmu_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSeikyuuUmu_2_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Seikyuu_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Seikyuu_2_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonAdd_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonAdd_2_2 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonDelete_2_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonDelete_2_2 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TrTysSyouhin_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTysSyouhin_2_3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenDbValue_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbValue_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgValue_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgValue_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenDbKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbKingaku_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgKingaku_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKbn_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHosyousyoNo_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHosyousyoNo_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBunruiCd_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunruiCd_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenZeiKbn_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiKbn_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUriDate_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriDate_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoKakuteiFlg_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKakuteiFlg_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoGaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoGaku_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenAutoKingakuFlg_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenAutoKingakuFlg_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenManualKingakuFlg_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenManualKingakuFlg_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBothKingakuChgFlg_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBothKingakuChgFlg_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysSeikyuuSaki_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysSeikyuuSaki_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSeikyuuSakiCd_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuSakiCd_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CheckAutoCalc_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckAutoCalc_2_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SPAN_Check_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Check_2_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKokyakuBangou_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKokyakuBangou_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenGamenHyoujiNo_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenHyoujiNo_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenRowDisplay_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenRowDisplay_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextNo_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNo_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSyouhin_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyouhin_2_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Syouhin_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Syouhin_2_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSelectSyouhin_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSelectSyouhin_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhinKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKingaku_2_3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucTokubetuTaiouToolTipCtrl_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ucTokubetuTaiouToolTipCtrl_2_3 As Global.Itis.Earth.WebUI.TokubetuTaiouToolTipCtrl

    '''<summary>
    '''TextUriageSyori_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageSyori_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKoumutenKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoumutenKingaku_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextJituSeikyuuKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJituSeikyuuKingaku_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyoudakusyoKingaku_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyoudakusyoKingaku_2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSeikyuuUmu_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSeikyuuUmu_2_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Seikyuu_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Seikyuu_2_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonAdd_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonAdd_2_3 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonDelete_2_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonDelete_2_3 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TrTysSyouhin_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrTysSyouhin_2_4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenDbValue_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbValue_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgValue_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgValue_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenDbKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbKingaku_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenChgKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenChgKingaku_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKbn_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHosyousyoNo_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHosyousyoNo_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBunruiCd_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunruiCd_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenZeiKbn_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiKbn_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenUriDate_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriDate_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoKakuteiFlg_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKakuteiFlg_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoGaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoGaku_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenAutoKingakuFlg_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenAutoKingakuFlg_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenManualKingakuFlg_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenManualKingakuFlg_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBothKingakuChgFlg_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBothKingakuChgFlg_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysSeikyuuSaki_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysSeikyuuSaki_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSeikyuuSakiCd_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuSakiCd_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CheckAutoCalc_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckAutoCalc_2_4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SPAN_Check_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Check_2_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKokyakuBangou_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKokyakuBangou_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenGamenHyoujiNo_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenHyoujiNo_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenRowDisplay_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenRowDisplay_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextNo_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextNo_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSyouhin_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyouhin_2_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Syouhin_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Syouhin_2_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSelectSyouhin_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSelectSyouhin_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSyouhinKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKingaku_2_4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucTokubetuTaiouToolTipCtrl_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ucTokubetuTaiouToolTipCtrl_2_4 As Global.Itis.Earth.WebUI.TokubetuTaiouToolTipCtrl

    '''<summary>
    '''TextUriageSyori_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageSyori_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKoumutenKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoumutenKingaku_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextJituSeikyuuKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJituSeikyuuKingaku_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyoudakusyoKingaku_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyoudakusyoKingaku_2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSeikyuuUmu_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSeikyuuUmu_2_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN_Seikyuu_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN_Seikyuu_2_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonAdd_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonAdd_2_4 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonDelete_2_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonDelete_2_4 As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
