'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5477
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''IraiCtrl1 クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class IraiCtrl1

    '''<summary>
    '''ScriptManagerProxy1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''btn_irai1_act コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_irai1_act As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''irai1MainUpdatePanel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1MainUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''iraiSessionKey コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents iraiSessionKey As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''actMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents actMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''updateDateTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents updateDateTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateUserId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateUserNm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateUserNm As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lastUpdateDateTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lastUpdateDateTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''errorData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents errorData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''kakuninOpenFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kakuninOpenFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''dateYesterday コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents dateYesterday As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSesyumeiOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSesyumeiOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenJuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenJuusyo1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyoriKensuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyoriKensuu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenRentouBukkenSuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenRentouBukkenSuu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenInsTokubetuTaiouFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenInsTokubetuTaiouFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSinkiTourokuMotoKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSinkiTourokuMotoKbn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''irai1DispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1DispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btn_irai1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_irai1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''irai1TitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1TitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonSearchFcMousikomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchFcMousikomi As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonSearchMousikomi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSearchMousikomi As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonBukkenRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBukkenRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonKousinRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKousinRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonTyousaMitsumorisyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTyousaMitsumorisyo As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonHosyousyoDB コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHosyousyoDB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonRJHS コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonRJHS As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''irai1TBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1TBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cboKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboKubun As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''spanKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents spanKubun As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnHoshoushoNoSaiban コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnHoshoushoNoSaiban As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hoshoushoNoSaiban コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hoshoushoNoSaiban As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanel_irai2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel_irai2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hoshouNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hoshouNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''spanHakiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents spanHakiDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cboDataHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboDataHaki As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''spanDataHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents spanDataHaki As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''changeHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents changeHaki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hakiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hakiDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''seshuName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents seshuName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RadioSesyumei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSesyumei1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSesyumei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSesyumei1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioSesyumei0 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSesyumei0 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSesyumei0 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSesyumei0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextJyutyuuBukkenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJyutyuuBukkenMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''bukkenJyuusho1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents bukkenJyuusho1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''bukkenJyuusho2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents bukkenJyuusho2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''UpdatePanel3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''choufukuCheck コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents choufukuCheck As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnChoufukuCheck コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnChoufukuCheck As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''choufukuKakuninFlg1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents choufukuKakuninFlg1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''choufukuKakuninFlg2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents choufukuKakuninFlg2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''choufukuKakuninTargetId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents choufukuKakuninTargetId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''bukkenJyuusho3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents bukkenJyuusho3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''juushoTenki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents juushoTenki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''bikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents bikou As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''bikou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents bikou2 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextBunjouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBunjouCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CheckBunjouCdSaiban コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckBunjouCdSaiban As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanBunjouCdSaiban コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanBunjouCdSaiban As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonBunjouSaiban コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBunjouSaiban As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''HiddenDbUpdDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenDbUpdDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBunjouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunjouCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSaibanNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSaibanNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TextBukkenNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBukkenNayoseCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''keiyu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents keiyu As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''SPAN1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''kashi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kashi As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''SPAN2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tyousakaisyaRenraku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousakaisyaRenraku As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tyousakaisyaTel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousakaisyaTel As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tyousakaisyaFax コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousakaisyaFax As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tyousakaisyaTantou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousakaisyaTantou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tyousakaisyaMailAddr コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousakaisyaMailAddr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''iraiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents iraiDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''setIraiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents setIraiDate As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''keiyakuNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents keiyakuNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chousaKibouDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chousaKibouDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CheckYoyakuZumi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckYoyakuZumi As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckYoyakuZumi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckYoyakuZumi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chousaKibouTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chousaKibouTime As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tatiai_cd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiai_cd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tatiai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiai As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN17 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN17 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatiaisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiaisya As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatiaiDiv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiaiDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatiaiSha_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiaiSha_1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Span3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Span3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatiaiSha_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiaiSha_2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Span6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Span6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatiaiSha_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatiaiSha_3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Span7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Span7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''kouzou_cd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kouzou_cd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboKouzou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboKouzou As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN12 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblKouzouSonota コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblKouzouSonota As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''kouzouSonota コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kouzouSonota As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''kaisou_cd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kaisou_cd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboKaisou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboKaisou As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sintikuTatekae_cd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents sintikuTatekae_cd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboShintikuTatekae コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboShintikuTatekae As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN10 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sijiryoku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents sijiryoku As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''iraiYoteiTousu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents iraiYoteiTousu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''negiri コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents negiri As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''morituti コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents morituti As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''yoteiKiso_cd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents yoteiKiso_cd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboYoteiKiso コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboYoteiKiso As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN14 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN14 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblYoteiKisoSonota コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblYoteiKisoSonota As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yoteiKisoSonota コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents yoteiKisoSonota As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboSyako コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents cboSyako As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SPAN13 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SPAN13 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''shoudakuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents shoudakuUmu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Span8 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Span8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''shoudakuChousaDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents shoudakuChousaDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CheckAnnaiZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckAnnaiZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckAnnaiZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckAnnaiZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckHaitiZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckHaitiZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckHaitiZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckHaitiZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckKakukaiHeimenZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckKakukaiHeimenZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckKakukaiHeimenZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckKakukaiHeimenZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckKisoHuseZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckKisoHuseZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckKisoHuseZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckKisoHuseZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckKisoDanmenZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckKisoDanmenZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckKisoDanmenZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckKisoDanmenZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckZouseiKeikakuZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CheckZouseiKeikakuZu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SpanCheckZouseiKeikakuZu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanCheckZouseiKeikakuZu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKisoTyakkouYoteiDateFrom コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKisoTyakkouYoteiDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKisoTyakkouYoteiDateTo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKisoTyakkouYoteiDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''iraiST コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents iraiST As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Irai1DataStr コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Irai1DataStr As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Irai2DataStr コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Irai2DataStr As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Irai2DdlDataStr コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Irai2DdlDataStr As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''irai1Mode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai1Mode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''irai2Mode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents irai2Mode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''exeMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents exeMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''jibanData コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents jibanData As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
