'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3615
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Syouhin4RecordCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class Syouhin4RecordCtrl

    '''<summary>
    '''TrSyouhin4Record コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TrSyouhin4Record As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HiddenKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKubun As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBangou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBunruiCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBunruiCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenGamenHyoujiNo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenGamenHyoujiNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenLoginUserId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenLoginUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUpdDatetime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUpdDatetime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenIraiGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenIraiGyoumuKengen As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHattyuusyoKanriKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKanriKengen As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKeiriGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiriGyoumuKengen As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKingakuFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKingakuFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUriageJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriageJyoukyou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUriageKeijyouDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenUriageKeijyouDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenBikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBikou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenIkkatuNyuukinFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenIkkatuNyuukinFlg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSeikyuuType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKeiretu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiretu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHattyuusyoKakuteiOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKakuteiOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHattyuusyoFlgOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoFlgOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenHattyuusyoKingakuOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKingakuOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyouhinKbn3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKbn3 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenJibanTysKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenJibanTysKaisyaCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyouhinCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinCdOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyouhin4SearchType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhin4SearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenZeikubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeikubun As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenZeiritu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenZeiritu As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKakuteiOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKakuteiOld As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenOpenValuesUriage コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenOpenValuesUriage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenOpenValuesSiire コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenOpenValuesSiire As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhinCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSyouhinKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSyouhinKensaku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonHiddenSyouhinKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHiddenSyouhinKensaku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''SelectKakutei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectKakutei As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanKakutei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanKakutei As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ucSeikyuuSiireLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ucSeikyuuSiireLink As Global.Itis.Earth.WebUI.SeikyuuSiireLinkCtrl

    '''<summary>
    '''SpanSyouhinMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyouhinMei As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Td1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextSyoudakusyoKingaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyoudakusyoKingaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSiireSyouhizeiGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSiireSyouhizeiGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TdDenpyouSiireNengappi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdDenpyouSiireNengappi As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TextDenpyouSiireNengappiDisplay コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireNengappiDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDenpyouSiireNengappi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouSiireNengappi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextKoumutenSeikyuuGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoumutenSeikyuuGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextJituSeikyuuGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJituSeikyuuGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextMitumorisyoSakuseiDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextMitumorisyoSakuseiDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSyouhizeiGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSyouhizeiGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextZeikomiKingaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextZeikomiKingaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDenpyouUriageNengappiDisplay コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouUriageNengappiDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDenpyouUriageNengappi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDenpyouUriageNengappi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextUriageNengappi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageNengappi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectUriageSyori コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectUriageSyori As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanUriageSyori コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanUriageSyori As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextUriageDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextUriageDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextSeikyuusyoHakkouDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSeikyuusyoHakkouDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectSeikyuuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSeikyuuUmu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanSeikyuuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSeikyuuUmu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextHattyuusyoKingaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHattyuusyoKingaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SelectHattyuusyoKakutei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectHattyuusyoKakutei As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanHattyuusyoKakutei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHattyuusyoKakutei As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextHattyuusyoKakuninDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextHattyuusyoKakuninDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTargetId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTargetId As Global.System.Web.UI.WebControls.HiddenField
End Class
