'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TeibetuSyouhin3Ctrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class TeibetuSyouhin3Ctrl

    '''<summary>
    '''Syouhin3Header コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Header As Global.Itis.Earth.WebUI.TeibetuSyouhinHeaderCtrl

    '''<summary>
    '''trSyouhin3Record01 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record01 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record01 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record01 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record02 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record02 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record02 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record02 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record03 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record03 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record03 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record03 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record04 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record04 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record04 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record04 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record05 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record05 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record05 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record05 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record06 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record06 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record06 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record06 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record07 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record07 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record07 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record07 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record08 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record08 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record08 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record08 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''trSyouhin3Record09 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents trSyouhin3Record09 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Syouhin3Record09 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Syouhin3Record09 As Global.Itis.Earth.WebUI.TeibetuSyouhinRecordCtrl

    '''<summary>
    '''HiddenKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKubun As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenBangou As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuusyoKanriKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuusyoKanriKengen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeiriGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiriGyoumuKengen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenLoginUserId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenLoginUserId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelIraiInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelIraiInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HiddenSeikyuuType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiretuCd As Global.System.Web.UI.WebControls.HiddenField
End Class
