'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3615
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TeibetuSyouhinHeaderCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class TeibetuSyouhinHeaderCtrl

    '''<summary>
    '''TdSyouhinCdTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSyouhinCdTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSyoudakusyoTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSyoudakusyoTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdDenpyouSiireNengappiTitleDisplay コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdDenpyouSiireNengappiTitleDisplay As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSpacer コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSpacer As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSyouhinNmTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSyouhinNmTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSiireSyouhizeiGakuTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdSiireSyouhizeiGakuTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdDenpyouSiireNengappiTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdDenpyouSiireNengappiTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdUriageSyoriTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TdUriageSyoriTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SpanSeikyuuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSeikyuuUmu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
