'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TeibetuKyoutuuCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class TeibetuKyoutuuCtrl

    '''<summary>
    '''KyoutuuDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KyoutuuDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''KyoutuuTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KyoutuuTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonBukkenRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBukkenRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonKousinRireki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKousinRireki As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonHosyousyoDB コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonHosyousyoDB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TBodyKyotuInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TBodyKyotuInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKubun As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBangou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextSesyuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextSesyuMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJyuusyo1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJyuusyo2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextJyuusyo3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJyuusyo3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextBikou1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBikou1 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextBikou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextBikou2 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextTyousaJissibi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaJissibi As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKairyouKoujiJissibi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKairyouKoujiJissibi As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKairyouKoujiKankou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKairyouKoujiKankou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTuikaKoujiJissibi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTuikaKoujiJissibi As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTuikaKoujiKankou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTuikaKoujiKankou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKaisekiTantouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKaisekiTantouCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKaisekiTantouMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKaisekiTantouMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKoujiTantouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoujiTantouCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextKoujiTantouMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKoujiTantouMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SpanHantei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHantei1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpanHanteiSetuzoku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHanteiSetuzoku As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SpanHantei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHantei2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenKeiriGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiriGyoumuKengen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenOpenValue コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenOpenValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeyValue コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeyValue As Global.System.Web.UI.WebControls.HiddenField
End Class
