'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3625
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TeibetuIraiNaiyouCtrl クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class TeibetuIraiNaiyouCtrl

    '''<summary>
    '''ScriptManagerProxy コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ScriptManagerProxy As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''IraiDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IraiDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''IraiTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents IraiTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TBodyIrai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TBodyIrai As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanelKameiten コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelKameiten As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SpanTyousaMitumoriFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanTyousaMitumoriFlg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKameitenTyuuiJikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenTyuuiJikou As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenKameitenTyuuiJikouPre コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKameitenTyuuiJikouPre As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonKameitenKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKameitenKensaku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextKameitenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKameitenMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTorikesiRiyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTorikesiRiyuu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ButtonKameitenTyuuijouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonKameitenTyuuijouhou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''SpanHattyuusyoFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanHattyuusyoFlg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextKeiretuNm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextKeiretuNm As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextEigyousyoMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextEigyousyoMei As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextJioSakiFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextJioSakiFlg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKbn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiretuCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenEigyousyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenEigyousyoCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysSeikyuuSaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysSeikyuuSaki As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHansokuSeikyuuSaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHansokuSeikyuuSaki As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenSeikyuuType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSeikyuuType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHansokuSeikyuuType コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHansokuSeikyuuType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenkameitenCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenkameitenCdOld As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelSyouhinKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhinKbn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadioSyouhinKbn1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSyouhinKbn1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSyouhinKbn1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyouhinKbn1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioSyouhinKbn2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSyouhinKbn2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSyouhinKbn2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyouhinKbn2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioSyouhinKbn3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSyouhinKbn3 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSyouhinKbn3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyouhinKbn3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioSyouhinKbn9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RadioSyouhinKbn9 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SpanSyouhinKbn9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSyouhinKbn9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''itemKbPre コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents itemKbPre As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSyouhinKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhinKbn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextDoujiIraiTousuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextDoujiIraiTousuu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextTatemonoYoutoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTatemonoYoutoCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SelectTatemonoYouto コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectTatemonoYouto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanelTysKaisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelTysKaisya As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTyousaKaishaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaKaishaCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ButtonTyousaKaishaKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonTyousaKaishaKensaku As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TextTyousaKaishaNm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaKaishaNm As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenTysKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaJigyousyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaJigyousyoCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaNg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaNg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaCdOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaCdOld As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenTysKaisyaNmOld コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTysKaisyaNmOld As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelSyouhin1Set コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhin1Set As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ButtonSetSyouhin1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSetSyouhin1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ButtonSetSyouhin1TysGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonSetSyouhin1TysGaiyou As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''UpdatePanelSyouhin1Seikyuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhin1Seikyuu As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HiddenJituSeikyuuGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenJituSeikyuuGaku As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKoumutenSeikyuugaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKoumutenSeikyuugaku As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextStatusIf コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextStatusIf As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenStatusIf コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenStatusIf As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''UpdatePanelSyouhin1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelSyouhin1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SelectSyouhin1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectSyouhin1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SpanSISyouhin1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpanSISyouhin1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HiddenSyouhin1Pre コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenSyouhin1Pre As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''UpdatePanelTyousaHouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelTyousaHouhou As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextTyousaHouhouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TextTyousaHouhouCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SelectTyousaHouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectTyousaHouhou As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HiddenTyousaHouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaHouhou As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelTyousaGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelTyousaGaiyou As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SelectTyousaGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SelectTyousaGaiyou As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''HiddenTyousaGaiyouCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaGaiyouCd As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HiddenTyousaGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenTyousaGaiyou As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeiriGyoumuKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeiriGyoumuKengen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenHattyuuKingaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenHattyuuKingaku As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenOpenValue コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenOpenValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenKeyValue コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HiddenKeyValue As Global.System.Web.UI.WebControls.HiddenField
End Class
