Imports System.Data.SqlClient
Imports System.Text
Imports Itis.ApplicationBlocks.Data.SQLHelper
''' <summary>請求先元帳帳票出力処理</summary>
''' <history>
''' <para>2010/07/14　王霽陽(大連情報システム部)　新規作成</para>
''' </history>
Public Class SeikyuSakiMototyouOutputDataAccess

    'EMAB障害対応情報格納処理
    Private ReadOnly ASSEMBLY_CLASSNAME As String = Me.GetType.FullName
    Private connDBUser As String = System.Configuration.ConfigurationManager.AppSettings("connDBUser").ToString

#Region "メンバ変数"
    Dim connStr As String = ConnectionManager.Instance.ConnectionString
#End Region

#Region "請求先元帳"

#Region "請求先元帳_繰越残高取得"
    ''' <summary>「繰越残高」を取得する</summary>
    ''' <param name="strSeikyuuSakiCd"> 請求先コード</param>
    ''' <param name="strSeikyuuSakiBrc"> 請求先枝番</param>
    ''' <param name="strSeikyuuSakiKbn"> 請求先区分</param>
    ''' <param name="strFromDate"> 抽出期間FROM(YYYY/MM/DD)</param>
    ''' <returns>繰越残高のデータ</returns>
    Public Function SelKurikosiZandaData(ByVal strSeikyuuSakiCd As String, ByVal strSeikyuuSakiBrc As String, ByVal strSeikyuuSakiKbn As String, ByVal strFromDate As String) As Data.DataTable
        ' DataSetインスタンスの生成()
        Dim dsSeikyuSakiMototyouDataSet As New Data.DataSet
        dsSeikyuSakiMototyouDataSet.Tables.Add()

        'SQL文の生成
        Dim commandTextSb As New StringBuilder

        'パラメータ格納
        Dim paramList As New List(Of SqlClient.SqlParameter)

        'SQL文
        With commandTextSb

            .AppendLine("SELECT                                                                                                                                       ")
            .AppendLine("    ISNULL(tkurikosi.tougetu_kurikosi_zan, 0) +                                                                                              ")
            .AppendLine("      ISNULL(tkurikosi.uriage_goukei, 0) - ISNULL(tkurikosi.nyuukin_goukei, 0) kurikosi_zan                                                  ")
            .AppendLine("FROM                                                                                                                                         ")
            .AppendLine("    (                                                                                                                                        ")
            .AppendLine("        SELECT                                                                                                                               ")
            .AppendLine("            sm.seikyuu_saki_cd                                                                                                               ")
            .AppendLine("            , sm.seikyuu_saki_brc                                                                                                            ")
            .AppendLine("            , sm.seikyuu_saki_kbn                                                                                                            ")
            .AppendLine("            , (     --売上額合計(売掛金データテーブル.当月繰越残高 の期間は除外)                                                                 ")
            .AppendLine("                SELECT                                                                                                                       ")
            .AppendLine("                    sum(isnull(u2.uri_gaku, 0)) + sum(isnull(u2.sotozei_gaku, 0)) kurikosi_zan                                               ")
            .AppendLine("                FROM                                                                                                                         ")
            .AppendLine("                    t_uriage_data u2                                                                                                         ")
            .AppendLine("                WHERE                                                                                                                        ")
            .AppendLine("                    u2.seikyuu_saki_cd = sm.seikyuu_saki_cd                                                                                  ")
            .AppendLine("                    AND u2.seikyuu_saki_brc = sm.seikyuu_saki_brc                                                                            ")
            .AppendLine("                    AND u2.seikyuu_saki_kbn = sm.seikyuu_saki_kbn                                                                            ")
            .AppendLine("                    AND u2.denpyou_uri_date BETWEEN DATEADD(                                                                                 ")
            .AppendLine("                        DAY                                                                                                                  ")
            .AppendLine("                        , + 1                                                                                                                ")
            .AppendLine("                        , ISNULL(ukt.taisyou_nengetu, '1900/1/1')                                                                            ")
            .AppendLine("                    ) AND DATEADD(DAY, - 1, @fromDate)                                                                                       ")

            '2010/10/07 売上データは、売上処理FLG=1のみ対象とする 馬艶軍追加 ↓
            .AppendLine("		                AND  ")
            .AppendLine("			                ISNULL(u2.uri_keijyou_flg,'0') = '1'  ")
            '2010/10/07 売上データは、売上処理FLG=1のみ対象とする 馬艶軍追加 ↑

            .AppendLine("            ) uriage_goukei                                                                                                                  ")
            .AppendLine("            , (    --入金額合計(売掛金データテーブル.当月繰越残高 の期間は除外)                                                                  ")
            .AppendLine("                SELECT                                                                                                                       ")
            .AppendLine("                    sum(isnull(n2.genkin, 0)) + sum(isnull(n2.kogitte, 0)) + sum(isnull(n2.furikomi, 0)) + sum(isnull(n2.tegata, 0))         ")
            .AppendLine("                    + sum(isnull(n2.sousai, 0)) + sum(isnull(n2.nebiki, 0)) + sum(isnull(n2.sonota, 0)) + sum(isnull(n2.kyouryoku_kaihi, 0)) ")
            .AppendLine("                    + sum(isnull(n2.kouza_furikae, 0)) + sum(isnull(n2.furikomi_tesuuryou, 0)) kurikosi_zan                                  ")
            .AppendLine("                FROM                                                                                                                         ")
            .AppendLine("                    t_nyuukin_data n2                                                                                                        ")
            .AppendLine("                WHERE                                                                                                                        ")
            .AppendLine("                    n2.seikyuu_saki_cd = sm.seikyuu_saki_cd                                                                                  ")
            .AppendLine("                    AND n2.seikyuu_saki_brc = sm.seikyuu_saki_brc                                                                            ")
            .AppendLine("                    AND n2.seikyuu_saki_kbn = sm.seikyuu_saki_kbn                                                                            ")
            .AppendLine("                    AND n2.nyuukin_date BETWEEN DATEADD(                                                                                     ")
            .AppendLine("                        DAY                                                                                                                  ")
            .AppendLine("                        , + 1                                                                                                                ")
            .AppendLine("                        , ISNULL(ukt.taisyou_nengetu, '1900/1/1')                                                                            ")
            .AppendLine("                    ) AND DATEADD(DAY, - 1, @fromDate)                                                                                       ")
            .AppendLine("            ) nyuukin_goukei                                                                                                                 ")
            .AppendLine("            , ukt.tougetu_kurikosi_zan                                                                                                       ")
            .AppendLine("        FROM                                                                                                                                 ")
            .AppendLine("            m_seikyuu_saki sm                                                                                                                ")
            .AppendLine("            LEFT OUTER JOIN (   --売掛金データテーブル.当月繰越残高取得                                                                         ")
            .AppendLine("                SELECT                                                                                                                       ")
            .AppendLine("                    uk.taisyou_nengetu                                                                                                       ")
            .AppendLine("                    , uk.seikyuu_saki_cd                                                                                                     ")
            .AppendLine("                    , uk.seikyuu_saki_brc                                                                                                    ")
            .AppendLine("                    , uk.seikyuu_saki_kbn                                                                                                    ")
            .AppendLine("                    , uk.tougetu_kurikosi_zan                                                                                                ")
            .AppendLine("                FROM                                                                                                                         ")
            .AppendLine("                    t_urikake_data uk                                                                                                        ")
            .AppendLine("                    LEFT OUTER JOIN (                                                                                                        ")
            .AppendLine("                        SELECT                                                                                                               ")
            .AppendLine("                            seikyuu_saki_cd                                                                                                  ")
            .AppendLine("                            , seikyuu_saki_brc                                                                                               ")
            .AppendLine("                            , seikyuu_saki_kbn                                                                                               ")
            .AppendLine("                            , max(taisyou_nengetu) taisyou_nengetu                                                                           ")
            .AppendLine("                        FROM                                                                                                                 ")
            .AppendLine("                            t_urikake_data                                                                                                   ")
            .AppendLine("                        WHERE                                                                                                                ")
            .AppendLine("                            taisyou_nengetu <= " & connDBUser & "fnGetLastDay(DATEADD(MONTH, - 1, @fromDate)) --指定日の月末日を取得する関数                ")
            .AppendLine("                        GROUP BY                                                                                                             ")
            .AppendLine("                            seikyuu_saki_cd                                                                                                  ")
            .AppendLine("                            , seikyuu_saki_brc                                                                                               ")
            .AppendLine("                            , seikyuu_saki_kbn                                                                                               ")
            .AppendLine("                    ) ukm                                                                                                                    ")
            .AppendLine("                        ON uk.seikyuu_saki_cd = ukm.seikyuu_saki_cd                                                                          ")
            .AppendLine("                        AND uk.seikyuu_saki_brc = ukm.seikyuu_saki_brc                                                                       ")
            .AppendLine("                        AND uk.seikyuu_saki_kbn = ukm.seikyuu_saki_kbn                                                                       ")
            .AppendLine("                WHERE                                                                                                                        ")
            .AppendLine("                    uk.taisyou_nengetu = ukm.taisyou_nengetu                                                                                 ")
            .AppendLine("            ) ukt                                                                                                                            ")
            .AppendLine("                ON sm.seikyuu_saki_cd = ukt.seikyuu_saki_cd                                                                                  ")
            .AppendLine("                AND sm.seikyuu_saki_brc = ukt.seikyuu_saki_brc                                                                               ")
            .AppendLine("                AND sm.seikyuu_saki_kbn = ukt.seikyuu_saki_kbn                                                                               ")
            .AppendLine("    ) tkurikosi                                                                                                                              ")
            .AppendLine("WHERE                                                                                                                                        ")
            .AppendLine("    tkurikosi.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                                                           ")
            .AppendLine("    AND tkurikosi.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                                                             ")
            .AppendLine("    AND tkurikosi.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                                                             ")

        End With

        'パラメータの設定
        paramList.Add(MakeParam("@seikyuuSakiCd", SqlDbType.VarChar, 5, strSeikyuuSakiCd))   '請求先コード 
        paramList.Add(MakeParam("@seikyuuSakiBrc", SqlDbType.VarChar, 2, strSeikyuuSakiBrc)) '請求先枝番  
        paramList.Add(MakeParam("@seikyuuSakiKbn", SqlDbType.VarChar, 1, strSeikyuuSakiKbn)) '請求先区分 
        paramList.Add(MakeParam("@fromDate", SqlDbType.VarChar, 10, strFromDate))

        '検索実行
        FillDataset(connStr, CommandType.Text, commandTextSb.ToString(), dsSeikyuSakiMototyouDataSet, dsSeikyuSakiMototyouDataSet.Tables(0).TableName, paramList.ToArray)

        Return dsSeikyuSakiMototyouDataSet.Tables(0)

    End Function
#End Region

#Region "請求先元帳_伝票データ取得"

    ''' <summary>売上データテーブル、入金データテーブルデータを取得する</summary>
    ''' <param name="strSeikyuuSakiCd"> 請求先コード</param>
    ''' <param name="strSeikyuuSakiBrc"> 請求先枝番</param>
    ''' <param name="strSeikyuuSakiKbn"> 請求先区分</param>
    ''' <param name="strFromDate"> 抽出期間FROM(YYYY/MM/DD)</param>
    ''' <param name="strToDate"> 抽出期間TO(YYYY/MM/DD)</param>
    ''' <returns>売上、入金のデータ</returns>
    Public Function SelUriageNyukinData(ByVal strSeikyuuSakiCd As String, ByVal strSeikyuuSakiBrc As String, ByVal strSeikyuuSakiKbn As String, ByVal strFromDate As String, ByVal strToDate As String) As Data.DataTable
        ' DataSetインスタンスの生成()
        Dim dsSelUriageNyukinDataDataSet As New Data.DataSet
        dsSelUriageNyukinDataDataSet.Tables.Add()

        'SQL文の生成
        Dim commandTextSb As New StringBuilder

        'パラメータ格納
        Dim paramList As New List(Of SqlClient.SqlParameter)

        'SQL文
        With commandTextSb

            .AppendLine("SELECT                                                                                               ")
            .AppendLine("    denpyou_uri_date                                                                                 ")
            .AppendLine("    , kamoku                                                                                         ")
            .AppendLine("    , syouhin_cd                                                                                     ")
            .AppendLine("    , hinmei                                                                                         ")
            .AppendLine("    , kbnbangou                                                                                      ")
            .AppendLine("    , jutyuu_bukken_mei                                                                              ")
            .AppendLine("    , suu                                                                                            ")
            .AppendLine("    , tanka                                                                                          ")
            .AppendLine("    , uri_gaku                                                                                       ")
            .AppendLine("    , sotozei_gaku                                                                                   ")
            .AppendLine("    , kingaku                                                                                        ")
            .AppendLine("    , seikyuu_date                                                                                   ")
            .AppendLine("    , kaisyuu_yotei_date                                                                             ")
            .AppendLine("    , denpyou_no                                                                                     ")
            .AppendLine("FROM                                                                                                 ")
            .AppendLine("(                                                                                                    ")
            .AppendLine(" --売上データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tu.denpyou_uri_date                                                                             ")
            .AppendLine("     , '売上' kamoku                                                                                 ")
            .AppendLine("     , tu.syouhin_cd                                                                                 ")
            .AppendLine("     , tu.hinmei                                                                                     ")
            .AppendLine("     , tu.kbn + tu.bangou AS kbnbangou                                                               ")
            .AppendLine("     , tj.jutyuu_bukken_mei                                                                          ")
            .AppendLine("     , tu.suu                                                                                        ")
            .AppendLine("     , tu.tanka                                                                                      ")
            .AppendLine("     , tu.uri_gaku                                                                                   ")
            .AppendLine("     , tu.sotozei_gaku                                                                               ")
            .AppendLine("     , ISNULL(tu.uri_gaku,0) + ISNULL(tu.sotozei_gaku,0) kingaku                                     ")
            .AppendLine("     , tu.seikyuu_date                                                                               ")
            '2010/10/20 回収予定日の取得を変更 　趙東莉↓
            '.AppendLine("     , (                                                                                             ")
            '.AppendLine("         SELECT                                                                                      ")
            '.AppendLine("             konkai_kaisyuu_yotei_date                                                               ")
            '.AppendLine("         FROM                                                                                        ")
            '.AppendLine("             t_seikyuu_kagami                                                                        ")
            '.AppendLine("         WHERE                                                                                       ")
            '.AppendLine("             torikesi = 0                                                                            ")
            '.AppendLine("             AND seikyuusyo_no = tsm.seikyuusyo_no                                                   ")
            '.AppendLine("     ) kaisyuu_yotei_date                                                                            ")
            .AppendLine("     , ts.kaisyuu_yotei_date ")
            '2010/10/20 回収予定日の取得を変更 　趙東莉↑
            .AppendLine("     , tu.denpyou_no                                                                                 ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("    t_uriage_data tu                                                                                 ")
            .AppendLine(" LEFT OUTER JOIN t_jiban tj                                                                      ")
            .AppendLine("         ON tu.kbn = tj.kbn                                                                          ")
            .AppendLine("         AND tu.bangou = tj.hosyousyo_no                                                             ")
            '2010/10/20 回収予定日の取得を変更 　趙東莉↓
            '.AppendLine(" LEFT OUTER JOIN t_seikyuu_meisai tsm                                                            ")
            '.AppendLine("         ON tu.denpyou_unique_no = tsm.denpyou_unique_no                                             ")
            .AppendLine(" LEFT OUTER JOIN (")
            .AppendLine("                   SELECT")
            .AppendLine("                       tsm.denpyou_unique_no                   ")
            '2010/10/25 回収予定日を今回回収予定日に変更する 　付龍 ↓
            '.AppendLine("                       ,tsk.kaisyuu_yotei_date                 ")
            .AppendLine("                       ,tsk.konkai_kaisyuu_yotei_date AS kaisyuu_yotei_date ")
            '2010/10/25 回収予定日を今回回収予定日に変更する 　付龍 ↑
            .AppendLine("                   FROM                                        ")
            .AppendLine("                       " & connDBUser & "t_seikyuu_meisai tsm            ")
            .AppendLine("                   INNER JOIN                                  ")
            .AppendLine("                       " & connDBUser & "t_seikyuu_kagami tsk            ")
            .AppendLine("                   ON                                          ")
            .AppendLine("                       tsm.seikyuusyo_no = tsk.seikyuusyo_no   ")
            .AppendLine("                   AND                                         ")
            .AppendLine("                       tsk.torikesi = 0                        ")
            .AppendLine("                   ) ts                                        ")
            .AppendLine(" ON                                                            ")
            .AppendLine("   tu.denpyou_unique_no = ts.denpyou_unique_no                 ")
            '2010/10/20 回収予定日の取得を変更 　趙東莉↑
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tu.seikyuu_saki_cd = @seikyuuSakiCd        --請求先コード                                        ")
            .AppendLine("     AND tu.seikyuu_saki_brc = @seikyuuSakiBrc  --請求先枝番                                          ")
            .AppendLine("     AND tu.seikyuu_saki_kbn = @seikyuuSakiKbn  --請求先区分                                          ")
            .AppendLine("     AND tu.denpyou_uri_date BETWEEN @fromDate AND @toDate                                       ")

            '2010/10/07 売上データは、売上処理FLG=1のみ対象とする 馬艶軍追加 ↓
            .AppendLine("		                AND  ")
            .AppendLine("			                ISNULL(tu.uri_keijyou_flg,'0') = '1'  ")
            '2010/10/07 売上データは、売上処理FLG=1のみ対象とする 馬艶軍追加 ↑

            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '振込'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.furikomi,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.furikomi <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                       ")
            .AppendLine("     , '現金'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                        ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.genkin,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.genkin <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '小切手'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.kogitte,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.kogitte <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '手形'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.tegata,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.tegata <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '相殺'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.sousai,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.sousai <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '値引'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.nebiki,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.nebiki <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , 'その他'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.sonota,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.sonota <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '協力会費'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.kyouryoku_kaihi,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.kyouryoku_kaihi <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '口座振替'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.kouza_furikae,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.kouza_furikae <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(" UNION ALL                                                                                           ")
            .AppendLine(" --入金データテーブル取得内容                                                                          ")
            .AppendLine(" SELECT                                                                                              ")
            .AppendLine("     tn.nyuukin_date AS denpyou_uri_date                                                             ")
            .AppendLine("     , '入金'  AS kamoku                                                                             ")
            .AppendLine("     , NULL      AS syouhin_cd                                                                         ")
            .AppendLine("     , '振込手数料'  AS hinmei                                                                             ")
            .AppendLine("     , NULL      AS kbnbangou                                                                          ")
            .AppendLine("     , tn.tekiyou_mei AS jutyuu_bukken_mei                                                           ")
            .AppendLine("     , NULL AS suu                                                                                     ")
            .AppendLine("     , NULL AS tanka                                                                                   ")
            .AppendLine("     , NULL AS uri_gaku                                                                                ")
            .AppendLine("     , NULL AS sotozei_gaku                                                                            ")
            .AppendLine("     , ISNULL(tn.furikomi_tesuuryou,0)  AS kingaku                                                             ")
            .AppendLine("     , NULL AS seikyuu_date                                                                            ")
            .AppendLine("     , NULL AS kaisyuu_yotei_date                                                                      ")
            .AppendLine("     , tn.denpyou_no AS denpyou_no                                                                   ")
            .AppendLine(" FROM                                                                                                ")
            .AppendLine("     t_nyuukin_data tn                                                                                  ")
            .AppendLine(" WHERE                                                                                               ")
            .AppendLine("     tn.seikyuu_saki_cd = @seikyuuSakiCd       --請求先コード                                         ")
            .AppendLine("     AND tn.seikyuu_saki_brc = @seikyuuSakiBrc --請求先枝番                                           ")
            .AppendLine("     AND tn.seikyuu_saki_kbn = @seikyuuSakiKbn --請求先区分                                           ")
            .AppendLine("     AND tn.furikomi_tesuuryou <> 0                                                                            ")
            .AppendLine("     AND tn.nyuukin_date BETWEEN @fromDate AND @toDate                                               ")
            .AppendLine(") uriagenyukin                                                                                       ")
            .AppendLine("ORDER BY uriagenyukin.denpyou_uri_date,uriagenyukin.kamoku,uriagenyukin.denpyou_no                   ")

        End With

        'パラメータの設定
        paramList.Add(MakeParam("@seikyuuSakiCd", SqlDbType.VarChar, 5, strSeikyuuSakiCd))
        paramList.Add(MakeParam("@seikyuuSakiBrc", SqlDbType.VarChar, 2, strSeikyuuSakiBrc))
        paramList.Add(MakeParam("@seikyuuSakiKbn", SqlDbType.VarChar, 1, strSeikyuuSakiKbn))
        paramList.Add(MakeParam("@fromDate", SqlDbType.VarChar, 10, strFromDate))
        paramList.Add(MakeParam("@toDate", SqlDbType.VarChar, 10, strToDate))

        '検索実行
        FillDataset(connStr, CommandType.Text, commandTextSb.ToString(), dsSelUriageNyukinDataDataSet, dsSelUriageNyukinDataDataSet.Tables(0).TableName, paramList.ToArray)

        Return dsSelUriageNyukinDataDataSet.Tables(0)

    End Function
#End Region

#End Region

End Class
