Imports System.Data.SqlClient
Imports System.Data
Imports System.Text
Imports Itis.ApplicationBlocks.Data.SQLHelper
Imports Itis.ApplicationBlocks.Data
Public Class YosinJyouhouDataAccess
    ''' <summary>
    ''' 加盟店与信情報を取得する
    ''' </summary>
    ''' <param name="strKameitenCd">加盟店コード</param>
    ''' <returns></returns>
    ''' <remarks></remarks>
    ''' <history>
    ''' 2009/07/11　王穎(大連開発)　新規作成　P-*****
    ''' </history>
    Public Function SelYosinJyouhou(ByVal strKameitenCd As String) _
                                    As DataAccess.YosinJyouhouDataSet.YosinJyouhouTableDataTable

        '---  接続文字列  ---

        Dim sbSql As New StringBuilder
        Dim lstParam As New List(Of SqlClient.SqlParameter)
        Dim strCon As String = System.Configuration.ConfigurationManager.ConnectionStrings("EarthConnectionString").ConnectionString

        '---  返却値格納用データセット  ---
        Dim dsYoshinJyouhou As New DataAccess.YosinJyouhouDataSet

        With sbSql
            '---  Sql文の生成  ---
            '.AppendLine("SELECT tys.tys_seikyuu_saki")
            '.AppendLine(",	tys.seikyuu_saki_name1 AS tys_seikyuu_saki_name1")
            '.AppendLine(",	tys.seikyuu_saki_name2 AS tys_seikyuu_saki_name2")
            '.AppendLine(",	tys.nayose_saki_cd AS tys_nayose_saki")
            '.AppendLine(",	tys.nayose_saki_name1 AS tys_nayose_saki_name1")
            '.AppendLine(",	tys.nayose_saki_name2 AS tys_nayose_saki_name2")
            '.AppendLine(",	tys.keikoku_joukyou AS tys_keikoku_jyoukyou")
            '.AppendLine(",	tys.meisyou AS tys_keikoku")
            '.AppendLine(",	koj.koj_seikyuusaki")
            '.AppendLine(",	koj.seikyuu_saki_name1 AS koj_seikyuusaki_name1")
            '.AppendLine(",	koj.seikyuu_saki_name2 AS koj_seikyuusaki_name2")
            '.AppendLine(",	koj.nayose_saki_cd AS koj_nayosesaki")
            '.AppendLine(",	koj.nayose_saki_name1 AS koj_nayosesaki_name1")
            '.AppendLine(",	koj.nayose_saki_name2 AS koj_nayosesaki_name2")
            '.AppendLine(",	koj.keikoku_joukyou AS koj_keikoku_jyoukyou")
            '.AppendLine(",	koj.meisyou AS koj_keikoku")
            '.AppendLine(",	hsh.hansokuhin_seikyuusaki")
            '.AppendLine(",	hsh.seikyuu_saki_name1 AS hansokuhin_seikyuusaki_name1")
            '.AppendLine(",	hsh.seikyuu_saki_name2 AS hansokuhin_seikyuusaki_name2")
            '.AppendLine(",	hsh.nayose_saki_cd AS hansokuhin_nayosesaki")
            '.AppendLine(",	hsh.nayose_saki_name1 AS hansokuhin_nayosesaki_name1")
            '.AppendLine(",	hsh.nayose_saki_name2 AS hansokuhin_nayosesaki_name2")
            '.AppendLine(",	hsh.keikoku_joukyou AS hansokuhin_keikoku_jyoukyou")
            '.AppendLine(",	hsh.meisyou AS hansokuhin_keikoku")
            '.AppendLine("FROM ( SELECT")
            '.AppendLine("	A.tys_seikyuu_saki")
            '.AppendLine(",	B.seikyuu_saki_name1")
            '.AppendLine(",	B.seikyuu_saki_name2")
            '.AppendLine(",	B.nayose_saki_cd")
            '.AppendLine(",	C.nayose_saki_name1")
            '.AppendLine(",	C.keikoku_joukyou")
            '.AppendLine(",	C.nayose_saki_name2")
            '.AppendLine(",	D.meisyou")
            '.AppendLine(",	A.kameiten_cd")
            '.AppendLine("  FROM m_kameiten AS A ")
            '.AppendLine("  WITH (READCOMMITTED) ")
            '.AppendLine("  LEFT JOIN m_nayose AS B ")
            '.AppendLine("  ON A.tys_seikyuu_saki= B.seikyuu_saki_cd ")
            '.AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            '.AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            '.AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu=@meisyou_syubetu) AS D ")
            '.AppendLine("  ON C.keikoku_joukyou= D.code ")
            '.AppendLine("   WHERE ")
            '.AppendLine("      A.kameiten_cd = @kameiten_cd) AS tys")
            '.AppendLine("LEFT JOIN")
            '.AppendLine("(SELECT")
            '.AppendLine("	A.koj_seikyuusaki")
            '.AppendLine(",	B.seikyuu_saki_name1 ")
            '.AppendLine(",	B.seikyuu_saki_name2 ")
            '.AppendLine(",	B.nayose_saki_cd")
            '.AppendLine(",	C.nayose_saki_name1 ")
            '.AppendLine(",	C.nayose_saki_name2 ")
            '.AppendLine(",	C.keikoku_joukyou")
            '.AppendLine(",	D.meisyou")
            '.AppendLine(",	A.kameiten_cd")
            '.AppendLine("  FROM m_kameiten AS A ")
            '.AppendLine("  WITH (READCOMMITTED) ")
            '.AppendLine("  LEFT JOIN m_nayose AS B ")
            '.AppendLine("  ON A.koj_seikyuusaki= B.seikyuu_saki_cd ")

            '.AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            '.AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            '.AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu=@meisyou_syubetu) AS D ")
            '.AppendLine("  ON C.keikoku_joukyou= D.code ")
            '.AppendLine("   WHERE ")
            '.AppendLine("      A.kameiten_cd = @kameiten_cd) AS koj")
            '.AppendLine("ON tys.kameiten_cd=koj.kameiten_cd")
            '.AppendLine("LEFT JOIN")
            '.AppendLine("( SELECT")
            '.AppendLine("	A.hansokuhin_seikyuusaki")
            '.AppendLine(",	B.seikyuu_saki_name1 ")
            '.AppendLine(",	B.seikyuu_saki_name2 ")
            '.AppendLine(",	B.nayose_saki_cd ")
            '.AppendLine(",	C.nayose_saki_name1 ")
            '.AppendLine(",	C.nayose_saki_name2 ")
            '.AppendLine(",	C.keikoku_joukyou")
            '.AppendLine(",	D.meisyou ")
            '.AppendLine(",	A.kameiten_cd")
            '.AppendLine("  FROM m_kameiten AS A ")
            '.AppendLine("  WITH (READCOMMITTED) ")
            '.AppendLine("  LEFT JOIN m_nayose AS B ")
            '.AppendLine("  ON A.hansokuhin_seikyuusaki= B.seikyuu_saki_cd ")

            '.AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            '.AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            '.AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu=@meisyou_syubetu) AS D ")
            '.AppendLine("  ON C.keikoku_joukyou= D.code ")
            '.AppendLine("   WHERE ")
            '.AppendLine("      A.kameiten_cd = @kameiten_cd) AS hsh")
            '.AppendLine("ON tys.kameiten_cd=hsh.kameiten_cd")
            .AppendLine("SELECT ")
            .AppendLine("	tys.tys_seikyuu_saki_cd")
            .AppendLine(",	tys.tys_seikyuu_saki_brc")
            .AppendLine(",	tys.tys_seikyuu_saki_kbn")
            .AppendLine(",	tys.kameiten_seisiki_mei AS tys_seikyuu_saki_name1")
            .AppendLine(",	tys.kameiten_seisiki_mei_kana AS tys_seikyuu_saki_name2")
            .AppendLine(",	tys.nayose_saki_cd AS tys_nayose_saki")
            .AppendLine(",	tys.nayose_saki_name1 AS tys_nayose_saki_name1")
            .AppendLine(",	tys.nayose_saki_name2 AS tys_nayose_saki_name2")
            .AppendLine(",	tys.keikoku_joukyou AS tys_keikoku_jyoukyou")
            .AppendLine(",	tys.meisyou AS tys_keikoku")
            .AppendLine(",	koj.koj_seikyuu_saki_cd")
            .AppendLine(",	koj.koj_seikyuu_saki_brc")
            .AppendLine(",	koj.koj_seikyuu_saki_kbn")
            .AppendLine(",	koj.kameiten_seisiki_mei AS koj_seikyuusaki_name1")
            .AppendLine(",	koj.kameiten_seisiki_mei_kana AS koj_seikyuusaki_name2")
            .AppendLine(",	koj.nayose_saki_cd AS koj_nayosesaki")
            .AppendLine(",	koj.nayose_saki_name1 AS koj_nayosesaki_name1")
            .AppendLine(",	koj.nayose_saki_name2 AS koj_nayosesaki_name2")
            .AppendLine(",	koj.keikoku_joukyou AS koj_keikoku_jyoukyou")
            .AppendLine(",	koj.meisyou AS koj_keikoku")
            .AppendLine(",	hsh.hansokuhin_seikyuu_saki_cd")
            .AppendLine(",	hsh.hansokuhin_seikyuu_saki_brc")
            .AppendLine(",	hsh.hansokuhin_seikyuu_saki_kbn")
            .AppendLine(",	hsh.kameiten_seisiki_mei AS hansokuhin_seikyuusaki_name1")
            .AppendLine(",	hsh.kameiten_seisiki_mei_kana AS hansokuhin_seikyuusaki_name2")
            .AppendLine(",	hsh.nayose_saki_cd AS hansokuhin_nayosesaki")
            .AppendLine(",	hsh.nayose_saki_name1 AS hansokuhin_nayosesaki_name1")
            .AppendLine(",	hsh.nayose_saki_name2 AS hansokuhin_nayosesaki_name2")
            .AppendLine(",	hsh.keikoku_joukyou AS hansokuhin_keikoku_jyoukyou")
            .AppendLine(",	hsh.meisyou AS hansokuhin_keikoku")
            .AppendLine(",	tat.tatemono_seikyuu_saki_cd")
            .AppendLine(",	tat.tatemono_seikyuu_saki_brc")
            .AppendLine(",	tat.tatemono_seikyuu_saki_kbn")
            .AppendLine(",	tat.kameiten_seisiki_mei AS tatemono_seikyuusaki_name1")
            .AppendLine(",	tat.kameiten_seisiki_mei_kana AS tatemono_seikyuusaki_name2")
            .AppendLine(",	tat.nayose_saki_cd AS tatemono_nayosesaki")
            .AppendLine(",	tat.nayose_saki_name1 AS tatemono_nayosesaki_name1")
            .AppendLine(",	tat.nayose_saki_name2 AS tatemono_nayosesaki_name2")
            .AppendLine(",	tat.keikoku_joukyou AS tatemono_keikoku_jyoukyou")
            .AppendLine(",	tat.meisyou AS tatemono_keikoku")
            .AppendLine("")
            .AppendLine("FROM ( SELECT")
            .AppendLine("	A.tys_seikyuu_saki_cd")
            .AppendLine(",	A.tys_seikyuu_saki_brc")
            .AppendLine(",	A.tys_seikyuu_saki_kbn")
            .AppendLine(",	A.kameiten_seisiki_mei")
            .AppendLine(",	A.kameiten_seisiki_mei_kana")
            .AppendLine(",	C.nayose_saki_name1")
            .AppendLine(",	C.nayose_saki_name2")
            .AppendLine(",	B.nayose_saki_cd")
            .AppendLine(",	C.keikoku_joukyou")
            .AppendLine(",	D.meisyou")
            .AppendLine(",	A.kameiten_cd")
            .AppendLine("  FROM m_kameiten AS A ")
            .AppendLine("  WITH (READCOMMITTED) ")
            .AppendLine("  LEFT JOIN m_seikyuu_saki AS B ")
            .AppendLine("  ON A.tys_seikyuu_saki_cd= B.seikyuu_saki_cd ")
            .AppendLine("AND A.tys_seikyuu_saki_brc= B.seikyuu_saki_brc ")
            .AppendLine("AND A.tys_seikyuu_saki_kbn= B.seikyuu_saki_kbn ")
            .AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            .AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            .AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu='52') AS D ")
            .AppendLine("  ON C.keikoku_joukyou= D.code ")
            .AppendLine("WHERE  A.kameiten_cd = @kameiten_cd")
            .AppendLine(") AS tys")
            .AppendLine("LEFT JOIN")
            .AppendLine("( SELECT")
            .AppendLine("	A.koj_seikyuu_saki_cd")
            .AppendLine(",	A.koj_seikyuu_saki_brc")
            .AppendLine(",	A.koj_seikyuu_saki_kbn")
            .AppendLine(",	A.kameiten_seisiki_mei")
            .AppendLine(",	A.kameiten_seisiki_mei_kana")
            .AppendLine(",	C.nayose_saki_name1")
            .AppendLine(",	C.nayose_saki_name2")
            .AppendLine(",	B.nayose_saki_cd")
            .AppendLine(",	C.keikoku_joukyou")
            .AppendLine(",	D.meisyou")
            .AppendLine(",	A.kameiten_cd")
            .AppendLine("  FROM m_kameiten AS A ")
            .AppendLine("  WITH (READCOMMITTED) ")
            .AppendLine("  LEFT JOIN m_seikyuu_saki AS B ")
            .AppendLine("  ON A.koj_seikyuu_saki_cd= B.seikyuu_saki_cd ")
            .AppendLine("AND A.koj_seikyuu_saki_brc= B.seikyuu_saki_brc ")
            .AppendLine("AND A.koj_seikyuu_saki_kbn= B.seikyuu_saki_kbn ")
            .AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            .AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            .AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu='52') AS D ")
            .AppendLine("  ON C.keikoku_joukyou= D.code ")
            .AppendLine("WHERE  A.kameiten_cd = @kameiten_cd")
            .AppendLine(" ) AS koj")
            .AppendLine("ON tys.kameiten_cd=koj.kameiten_cd")
            .AppendLine("LEFT JOIN")
            .AppendLine("(SELECT")
            .AppendLine("	A.hansokuhin_seikyuu_saki_cd")
            .AppendLine(",	A.hansokuhin_seikyuu_saki_brc")
            .AppendLine(",	A.hansokuhin_seikyuu_saki_kbn")
            .AppendLine(",	A.kameiten_seisiki_mei")
            .AppendLine(",	A.kameiten_seisiki_mei_kana")
            .AppendLine(",	C.nayose_saki_name1")
            .AppendLine(",	C.nayose_saki_name2")
            .AppendLine(",	B.nayose_saki_cd")
            .AppendLine(",	C.keikoku_joukyou")
            .AppendLine(",	D.meisyou")
            .AppendLine(",	A.kameiten_cd")
            .AppendLine("  FROM m_kameiten AS A ")
            .AppendLine("  WITH (READCOMMITTED) ")
            .AppendLine("  LEFT JOIN m_seikyuu_saki AS B ")
            .AppendLine("  ON A.hansokuhin_seikyuu_saki_cd= B.seikyuu_saki_cd ")
            .AppendLine("AND A.hansokuhin_seikyuu_saki_brc= B.seikyuu_saki_brc ")
            .AppendLine("AND A.hansokuhin_seikyuu_saki_kbn= B.seikyuu_saki_kbn ")
            .AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            .AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            .AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu='52') AS D ")
            .AppendLine("  ON C.keikoku_joukyou= D.code ")
            .AppendLine("WHERE  A.kameiten_cd = @kameiten_cd")
            .AppendLine(") AS hsh")
            .AppendLine("ON tys.kameiten_cd=hsh.kameiten_cd")
            .AppendLine("LEFT JOIN")
            .AppendLine("(SELECT")
            .AppendLine("	A.tatemono_seikyuu_saki_cd")
            .AppendLine(",	A.tatemono_seikyuu_saki_brc")
            .AppendLine(",	A.tatemono_seikyuu_saki_kbn")
            .AppendLine(",	A.kameiten_seisiki_mei")
            .AppendLine(",	A.kameiten_seisiki_mei_kana")
            .AppendLine(",	C.nayose_saki_name1")
            .AppendLine(",	C.nayose_saki_name2")
            .AppendLine(",	B.nayose_saki_cd")
            .AppendLine(",	C.keikoku_joukyou")
            .AppendLine(",	D.meisyou")
            .AppendLine(",	A.kameiten_cd")
            .AppendLine("  FROM m_kameiten AS A ")
            .AppendLine("  WITH (READCOMMITTED) ")
            .AppendLine("  LEFT JOIN m_seikyuu_saki AS B ")
            .AppendLine("  ON A.tatemono_seikyuu_saki_cd= B.seikyuu_saki_cd ")
            .AppendLine("AND A.tatemono_seikyuu_saki_brc= B.seikyuu_saki_brc ")
            .AppendLine("AND A.tatemono_seikyuu_saki_kbn= B.seikyuu_saki_kbn ")
            .AppendLine("  LEFT JOIN m_yosinkanri AS C ")
            .AppendLine("  ON B.nayose_saki_cd= C.nayose_saki_cd ")
            .AppendLine("  LEFT JOIN (SELECT code,meisyou FROM m_meisyou WHERE meisyou_syubetu='52') AS D ")
            .AppendLine("  ON C.keikoku_joukyou= D.code ")
            .AppendLine("WHERE  A.kameiten_cd = @kameiten_cd")
            .AppendLine(") AS tat")
            .AppendLine("ON tys.kameiten_cd=tat.kameiten_cd")
        End With

        'パラメータ 
        lstParam.Add(MakeParam("@kameiten_cd", SqlDbType.VarChar, 5, strKameitenCd))
        lstParam.Add(MakeParam("@meisyou_syubetu", SqlDbType.Char, 2, 52))

        SQLHelper.FillDataset(strCon, CommandType.Text, _
        sbSql.ToString, _
        dsYoshinJyouhou, dsYoshinJyouhou.YosinJyouhouTable.TableName, lstParam.ToArray)

        lstParam.Clear()

        Return dsYoshinJyouhou.YosinJyouhouTable

    End Function

End Class
