'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3053
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''BukkenJyouhouInquiry クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class BukkenJyouhouInquiry

    '''<summary>
    '''tbxKameiTenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameiTenCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKameiTenName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameiTenName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTorikesi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKameiTenKana コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameiTenKana As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTantou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTantou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Table1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnSortHosyousyoNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyoNo1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortHosyousyoNo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyoNo2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortSesyuMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortSesyuMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortSesyuMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortSesyuMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divHeadRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHeadRight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSortBukkenJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortBukkenJyuusyo1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortBukkenJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortBukkenJyuusyo2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnKaisyaCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKaisyaCd1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnKaisyaCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKaisyaCd2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortIraiDate1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortIraiDate1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortIraiDate2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortIraiDate2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTysJissiDate1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTysJissiDate1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTysJissiDate2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTysJissiDate2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTysHkksHakDate1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTysHkksHakDate1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTysHkksHakDate2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTysHkksHakDate2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKsSiyou1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKsSiyou1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKsSiyou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKsSiyou2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGaisyaCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnGaisyaCd1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGaisyaCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnGaisyaCd2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKouhou1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKouhou1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKouhou2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKouhou2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKoj_hkks_hassou_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKoj_hkks_hassou_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKoj_hkks_hassou_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKoj_hkks_hassou_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortHosyousyo_hak_jyky1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyo_hak_jyky1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortHosyousyo_hak_jyky2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyo_hak_jyky2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortUriagegaku1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortUriagegaku1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortUriagegaku2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortUriagegaku2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnKaisyaMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKaisyaMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnKaisyaMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKaisyaMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortSyoudakusyo_tys_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortSyoudakusyo_tys_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortSyoudakusyo_tys_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortSyoudakusyo_tys_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKeikakusyo_sakusei_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKeikakusyo_sakusei_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKeikakusyo_sakusei_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKeikakusyo_sakusei_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTantousya_mei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTantousya_mei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTantousya_mei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTantousya_mei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGaisyaMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnGaisyaMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGaisyaMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnGaisyaMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_kanry_yotei_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_kanry_yotei_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_kanry_yotei_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_kanry_yotei_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_sokuhou_tyk_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_sokuhou_tyk_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKairy_koj_sokuhou_tyk_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKairy_koj_sokuhou_tyk_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKouji_tantousya_mei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKouji_tantousya_mei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKouji_tantousya_mei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKouji_tantousya_mei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortHosyousyo_hak_date1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyo_hak_date1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortHosyousyo_hak_date2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortHosyousyo_hak_date2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortNyukingaku1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortNyukingaku1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortNyukingaku2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortNyukingaku2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divBodyLeft コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divBodyLeft As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdBodyLeft コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdBodyLeft As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divBodyRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divBodyRight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdBodyRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdBodyRight As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divHiddenMeisaiV コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHiddenMeisaiV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblDivHMV コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tblDivHMV As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''divHiddenMeisaiH コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHiddenMeisaiH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblDivHMH コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tblDivHMH As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''tblButton コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tblButton As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnTojiru コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTojiru As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''kameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kameitenCd As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hidScroll コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidScroll As Global.System.Web.UI.WebControls.HiddenField
End Class
