'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5485
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''KanrisyaMenuInquiryInput クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class KanrisyaMenuInquiryInput

    '''<summary>
    '''buySelName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents buySelName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''disableDiv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents disableDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxUserCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxUserCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblLogonId コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblLogonId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSinjinKubun コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSinjinKubun As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxSiMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSiMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlGyoumuCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlGyoumuCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSyozokuBusyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblSyozokuBusyo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hidBusyoCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidBusyoCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Label1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSosikiLevel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblSosikiLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hidLevel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidLevel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlLevel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblYakusyoku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblYakusyoku As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlBusyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlBusyo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSansyouKengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblSansyouKengen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlIraiGyoumu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlIraiGyoumu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSinkiNyuryoku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSinkiNyuryoku As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDataHaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlDataHaki As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKekkagyoumu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKekkagyoumu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlHosyouGyoumu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlHosyouGyoumu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlHokosyoGyoumu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlHokosyoGyoumu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKouji コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKouji As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKeiriGyoumu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKeiriGyoumu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlHansokuUriage コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlHansokuUriage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlHattyusyoKanri コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlHattyusyoKanri As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKaisekiMaster コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKaisekiMaster As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEigyouMaster コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlEigyouMaster As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKakakuMaster コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKakakuMaster As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddltyousaka_kanrisya_kengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddltyousaka_kanrisya_kengen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlkensa_gyoumu_kengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlkensa_gyoumu_kengen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlhanyou1_gyoumu_kengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlhanyou1_gyoumu_kengen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlhanyou2_gyoumu_kengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlhanyou2_gyoumu_kengen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlhanyou3_gyoumu_kengen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlhanyou3_gyoumu_kengen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSystemKanrisya コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSystemKanrisya As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBack コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTouroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidHaita コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidHaita As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidbtnKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidbtnKbn As Global.System.Web.UI.WebControls.HiddenField
End Class
