'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3643
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''KensakuSyoukaiInquiry クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class KensakuSyoukaiInquiry

    '''<summary>
    '''buySelName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents buySelName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''disableDiv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents disableDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Common_drop1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Common_drop1 As Global.Itis.Earth.WebUI.common_drop

    '''<summary>
    '''Common_drop2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Common_drop2 As Global.Itis.Earth.WebUI.common_drop

    '''<summary>
    '''Common_drop3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Common_drop3 As Global.Itis.Earth.WebUI.common_drop

    '''<summary>
    '''chkKubunAll コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chkKubunAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTaikai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chkTaikai As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbxKameitenMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameitenMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKameitenCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameitenCd1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKameitenSearch1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKameitenSearch1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxKameitenCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameitenCd2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKameitenSearch2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKameitenSearch2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxKameitenKana コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKameitenKana As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxEigyousyoCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxEigyousyoCd1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEigyousyoSearch1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnEigyousyoSearch1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxEigyousyoCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxEigyousyoCd2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEigyousyoSearch2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnEigyousyoSearch2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxDenwaBangou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxDenwaBangou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTourokuNengetuhi1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTourokuNengetuhi1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTourokuNengetuhi2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTourokuNengetuhi2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Common_drop コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Common_drop As Global.Itis.Earth.WebUI.common_drop

    '''<summary>
    '''tbxKeiretuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKeiretuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKeiretuSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKeiretuSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxKeiretuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKeiretuMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkLitSoufusaki コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chkLitSoufusaki As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlSearchCount コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSearchCount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnKensaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKensaku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClearWin コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnClearWin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCount コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSortTorikesi1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTorikesi1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTorikesi2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTorikesi2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKubun1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKubun1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKubun2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKubun2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenCd1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenCd2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divHeadRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHeadRight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSortKameitenMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenKana1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenKana1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenKana2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenKana2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenMei21 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenMei21 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKameitenMei22 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKameitenMei22 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortJyuusyo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortJyuusyo1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortJyuusyo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortJyuusyo2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTourofukenMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTourofukenMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTourofukenMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTourofukenMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKeiretu1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKeiretu1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortKeiretu2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortKeiretu2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortEigyousyoCd1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortEigyousyoCd1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortEigyousyoCd2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortEigyousyoCd2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortBuilderNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortBuilderNo1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortBuilderNo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortBuilderNo2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortDaihyousyaMei1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortDaihyousyaMei1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortDaihyousyaMei2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortDaihyousyaMei2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTelNo1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTelNo1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSortTelNo2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSortTelNo2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divBodyLeft コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divBodyLeft As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdItiranLeft コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdItiranLeft As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divBodyRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divBodyRight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdItiranRight コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdItiranRight As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divHiddenMeisaiV コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHiddenMeisaiV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divHiddenMeisaiH コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHiddenMeisaiH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTouroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKihonJyouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKihonJyouhou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTyuiJikou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTyuiJikou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBukkenJyouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnBukkenJyouhou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnYosinJyouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnYosinJyouhou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKakakuJyouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKakakuJyouhou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSiharaiTyousa コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSiharaiTyousa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSiharaiKouji コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSiharaiKouji As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHoukakusyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnHoukakusyo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnIttukatu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnIttukatu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKihonJyouhouCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKihonJyouhouCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnJyusyoJyouhouCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnJyusyoJyouhouCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKameitenInfoIttukatuCsv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKameitenInfoIttukatuCsv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTorihukiJyoukenKakuninhyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTorihukiJyoukenKakuninhyou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTyousaCard コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTyousaCard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidKeiretuMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidKeiretuMei As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidScroll コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidScroll As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSentakuKameitenCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSentakuKameitenCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSentakuKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSentakuKbn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidFile コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidFile As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSelectRowIndex コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSelectRowIndex As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''file コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents file As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
