'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.42
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''KoujiKakakuMasterKobetuSettei クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class KoujiKakakuMasterKobetuSettei

    '''<summary>
    '''btnClose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTouroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlAiteSakiSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlAiteSakiSyubetu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxAiteSakiCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxAiteSakiCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAiteSakiCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAiteSakiCd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxAiteSakiMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxAiteSakiMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSyouhinCd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chkTorikesi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbxKojKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKojKaisyaCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxKojKaisyaMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKojKaisyaMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlKojGaisyaSeikyuuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKojGaisyaSeikyuuUmu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxUriGaku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxUriGaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSeikyuuUmu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSeikyuuUmu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdnKensakuFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnKensakuFlg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAiteSakiSyubetu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnAiteSakiSyubetu As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAiteSakiCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnAiteSakiCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnKensakuFlg2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnKensakuFlg2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnKojKaisyaCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnKojKaisyaCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDbFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdnDbFlg As Global.System.Web.UI.WebControls.HiddenField
End Class
