'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.1433
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''SeikyuuSakiTyuuijikouSearchList クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class SeikyuuSakiTyuuijikouSearchList

    '''<summary>
    '''buySelName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents buySelName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''disableDiv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents disableDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnClose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTouroku コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTouroku As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlSeikyuusakiKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSeikyuusakiKbn As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxSeikyuusakiCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSeikyuusakiCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCdBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblCdBrc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxSeikyuusakiBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSeikyuusakiBrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSeikyuusakiSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusakiSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxSeikyuusakiMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSeikyuusakiMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSyubetuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSyubetuCd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlJyuuyoudo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlJyuuyoudo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxSeikyuuSimeDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSeikyuuSimeDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxSeikyuusyoHittykDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSeikyuusyoHittykDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKensuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblKensuu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlKensaKensuu コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlKensaKensuu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnKensakujiltukou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKensakujiltukou As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkKensakuTaisyouGai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents chkKensakuTaisyouGai As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnCsvOutput コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnCsvOutput As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCount コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSeikyuusakiCdUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusakiCdUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSeikyuusakiCdDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusakiCdDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSeikyuusakiMeiUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusakiMeiUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSeikyuusakiMeiDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusakiMeiDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divTorikesi コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divTorikesi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnTorikesiUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTorikesiUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnTorikesiDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTorikesiDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSyubetuCdUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSyubetuCdUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSyubetuCdDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSyubetuCdDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSyousaiUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSyousaiUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSyousaiDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSyousaiDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divJyuuyoudo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divJyuuyoudo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnJyuuyoudoUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnJyuuyoudoUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnJyuuyoudoDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnJyuuyoudoDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divSeikyuuSimeDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divSeikyuuSimeDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSeikyuuSimeDateUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuuSimeDateUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSeikyuuSimeDateDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuuSimeDateDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divSeikyuusyoHittykDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divSeikyuusyoHittykDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSeikyuusyoHittykDateUp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusyoHittykDateUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSeikyuusyoHittykDateDown コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSeikyuusyoHittykDateDown As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divMeisai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divMeisai As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdMeisai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdMeisai As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divHiddenMeisaiV コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divHiddenMeisaiV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCsvSyori コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnCsvSyori As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidCSVFlg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidCSVFlg As Global.System.Web.UI.WebControls.HiddenField
End Class
