'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.1433
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''SyouhinKakakusetteiMaster クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class SyouhinKakakusetteiMaster

    '''<summary>
    '''buySelName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents buySelName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''disableDiv コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents disableDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnBack コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanelA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanelA As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TbHead コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TbHead As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ddlSyouhinKBN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlSyouhinKBN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTysHouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlTysHouhou As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTysGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ddlTysGaiyou As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSyouhinCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKensakuSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnKensakuSyouhinCd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbxSyouhinMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxSyouhinMei As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdHead コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdHead As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divMeisai コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents divMeisai As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents grdBody As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidTop コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidTop As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidBtn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidBtn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidBool コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidBool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnOpen コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnOpen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidSyouhinKBN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSyouhinKBN As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidTysHouhou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidTysHouhou As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidTysGaiyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidTysGaiyou As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSyouhinCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSyouhinCd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSetteiBasyo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidSetteiBasyo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidUPDTime コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidUPDTime As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidRowIndex コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidRowIndex As Global.System.Web.UI.WebControls.HiddenField
End Class
