'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.42
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''YosinJyouhouInquiry_aspx クラス。
'''</summary>
'''<remarks>
'''自動生成されたクラス。
'''</remarks>
Partial Public Class YosinJyouhouInquiry_aspx

    '''<summary>
    '''Kyoutuu_jyouhou1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Kyoutuu_jyouhou1 As Global.Itis.Earth.WebUI.kyoutuu_jyouhou

    '''<summary>
    '''tyousaDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousaDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tyousaTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tyousaTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''kyoutuTBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents kyoutuTBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxTyousaSeikyuuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaSeikyuuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaSeikyuuBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaSeikyuuBrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTyousaSeikyuuKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTyousaSeikyuuKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaSeikyuuName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaSeikyuuName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaSeikyuuName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaSeikyuuName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaNayoseCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaNayoseName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaNayoseName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTyousaNayose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTyousaNayose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxTyousaNayoseName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaNayoseName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTyousaYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTyousaYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTyousaYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTyousaYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''koujiDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents koujiDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''koujiTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents koujiTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''koujiTBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents koujiTBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxKoujiSeikyuuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiSeikyuuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiSeikyuuBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiSeikyuuBrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKoujiSeikyuuKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblKoujiSeikyuuKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiSeikyuuName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiSeikyuuName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiSeikyuuName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiSeikyuuName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiNayoseCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiNayoseName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiNayoseName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKoujiNayose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblKoujiNayose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxKoujiNayoseName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiNayoseName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxKoujiYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxKoujiYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKoujiYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblKoujiYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hansakuhinDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hansakuhinDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''hansakuhinTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hansakuhinTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hansakuhinTBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hansakuhinTBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxHansokuhinSeikyuuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinSeikyuuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinSeikyuuBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinSeikyuuBrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHansokuhinSeikyuuKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblHansokuhinSeikyuuKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinSeikyuuName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinSeikyuuName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinSeikyuuName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinSeikyuuName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinNayoseCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinNayoseName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinNayoseName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHansokuhinNayose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblHansokuhinNayose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxHansokuhinNayoseName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinNayoseName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxHansokuhinYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxHansokuhinYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHansokuhinYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblHansokuhinYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tatemonoDispLink コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatemonoDispLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tatemonoTitleInfobar コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatemonoTitleInfobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tatemonoTBody コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tatemonoTBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbxTatemonoSeikyuuCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoSeikyuuCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoSeikyuuBrc コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoSeikyuuBrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTatemonoSeikyuuKbn コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTatemonoSeikyuuKbn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoSeikyuuName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoSeikyuuName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoSeikyuuName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoSeikyuuName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoNayoseCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoNayoseName1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoNayoseName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTatemonoNayose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTatemonoNayose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxTatemonoNayoseName2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoNayoseName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxTatemonoYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents tbxTatemonoYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTatemonoYoshinKeikokuJyoukyou コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTatemonoYoshinKeikokuJyoukyou As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnTemp コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTemp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidNayoseCd コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidNayoseCd As Global.System.Web.UI.WebControls.HiddenField
End Class
