Imports System.text
Imports System.Data.SqlClient

''' <summary>
''' 進捗データに関係するデータアクセスクラスです
''' </summary>
''' <remarks></remarks>
Public Class ReportIfDataAccess

    'EMAB障害対応情報格納処理
    Private ReadOnly ASSEMBLY_CLASSNAME As String = Me.GetType.FullName

    ''' <summary>
    ''' コネクションストリング
    ''' </summary>
    ''' <remarks></remarks>
    Private connStr As String = ConnectionManager.Instance.ConnectionString

    ''' <summary>
    ''' 顧客番号を引数に存在チェックを行います
    ''' </summary>
    ''' <param name="kokyakuNo">顧客番号</param>
    ''' <returns>進捗データチェック用データテーブル</returns>
    ''' <remarks></remarks>
    Public Function GetReportIf(ByVal kokyakuNo As String) As ReportIfDataSet.ReportIfTableDataTable

        'メソッド名、引数の情報の退避
        UnTrappedExceptionManager.AddMethodEntrance(ASSEMBLY_CLASSNAME & ".GetReportIf", _
                                                    kokyakuNo)

        ' 戻り値
        Dim strReportIfYm As String = ""

        ' パラメータ
        Const strParamKokyakuNo As String = "@KUBUN"

        Dim commandTextSb As New StringBuilder()

        commandTextSb.Append("SELECT kokyaku_no, kokyaku_brc, ISNULL(syouken_no,'') AS syouken_no ")
        commandTextSb.Append("  FROM ReportIF WITH (UPDLOCK) ")
        commandTextSb.Append("  WHERE kokyaku_no = " & strParamKokyakuNo)
        commandTextSb.Append("  AND   kokyaku_brc = 0 ")

        ' パラメータへ設定
        Dim commandParameters() As SqlParameter = _
            {SQLHelper.MakeParam(strParamKokyakuNo, SqlDbType.VarChar, 20, kokyakuNo)}

        ' データの取得
        Dim ReportIfDataSet As New ReportIfDataSet()

        ' 検索実行
        SQLHelper.FillDataset(connStr, CommandType.Text, commandTextSb.ToString(), _
            ReportIfDataSet, ReportIfDataSet.ReportIfTable.TableName, commandParameters)

        Dim reportIfTable As ReportIfDataSet.ReportIfTableDataTable = ReportIfDataSet.ReportIfTable

        Return reportIfTable

    End Function

    ''' <summary>
    ''' 進捗データ編集モード
    ''' </summary>
    ''' <remarks></remarks>
    Public Enum EDIT_MODE
        ''' <summary>
        ''' 登録
        ''' </summary>
        ''' <remarks></remarks>
        MODE_INSERT = 0
        ''' <summary>
        ''' 更新
        ''' </summary>
        ''' <remarks></remarks>
        MODE_UPDATE = 1
    End Enum

    ''' <summary>
    ''' 進捗データテーブルの登録・更新を行います(名称はマスタから取得するVersion)
    ''' </summary>
    ''' <param name="reportRec">進捗データレコード</param>
    ''' <param name="editMode">処理モード</param>
    ''' <returns>更新結果</returns>
    ''' <remarks></remarks>
    Public Function EditReportIf(ByVal reportRec As ReportIfRecord, _
                                 ByVal editMode As EDIT_MODE) As Integer

        'メソッド名、引数の情報の退避
        UnTrappedExceptionManager.AddMethodEntrance(ASSEMBLY_CLASSNAME & ".EditReportIf", _
                                                    reportRec, _
                                                    editMode)

        Dim intResult As Integer = 0
        Dim cmdTextSb As New StringBuilder
        Dim cmdParams(IIf(editMode = EDIT_MODE.MODE_INSERT, 41, 40)) As SqlClient.SqlParameter

        'パラメータ設定
        cmdParams(0) = MakeParam("@KBN", SqlDbType.Char, 1, reportRec.KokyakuNo.Substring(0, 1))
        cmdParams(1) = MakeParam("@NO", SqlDbType.VarChar, 10, reportRec.KokyakuNo.Substring(1))
        cmdParams(2) = MakeParam("@CHOUSATACHIAI", SqlDbType.VarChar, 22, reportRec.ChousaTachiai)
        cmdParams(3) = MakeParam("@OPTIONS", SqlDbType.VarChar, 512, reportRec.Options)

        ' 登録モード の場合、Insert
        If editMode = EDIT_MODE.MODE_INSERT Then
            '追加
            cmdTextSb.Append(" INSERT INTO ")
            cmdTextSb.Append("      dbo.ReportIF ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      kokyaku_no ")
            cmdTextSb.Append("    , kokyaku_brc ")
            cmdTextSb.Append("    , service_kbn ")
            cmdTextSb.Append("    , tyousa ")
            cmdTextSb.Append("    , keikaku ")
            cmdTextSb.Append("    , sesyu_name ")
            cmdTextSb.Append("    , bkn_adr1 ")
            cmdTextSb.Append("    , bkn_adr2 ")
            cmdTextSb.Append("    , chousa_hope_date ")
            cmdTextSb.Append("    , chousa_hope_time ")
            cmdTextSb.Append("    , chousa_tanto ")
            cmdTextSb.Append("    , chousa_tachiai ")
            cmdTextSb.Append("    , kamei_cd ")
            cmdTextSb.Append("    , kamei_name ")
            cmdTextSb.Append("    , kamei_tel ")
            cmdTextSb.Append("    , kamei_fax ")
            cmdTextSb.Append("    , kamei_mail ")
            cmdTextSb.Append("    , tyousa_cd ")
            cmdTextSb.Append("    , tyousa_brc ")
            cmdTextSb.Append("    , tyousa_name ")
            cmdTextSb.Append("    , t_renraku_name ")
            cmdTextSb.Append("    , t_renraku_tel ")
            cmdTextSb.Append("    , t_renraku_fax ")
            cmdTextSb.Append("    , t_renraku_mail ")
            cmdTextSb.Append("    , t_renraku_tanto ")
            cmdTextSb.Append("    , tenmei_kana1 ")
            cmdTextSb.Append("    , kouzou ")
            cmdTextSb.Append("    , kaisou ")
            cmdTextSb.Append("    , sekkei_kyoyou_sijiryoku ")
            cmdTextSb.Append("    , negiri_hukasa ")
            cmdTextSb.Append("    , yotei_ks_mei ")
            cmdTextSb.Append("    , syako ")
            cmdTextSb.Append("    , yotei_morituti_atusa ")
            cmdTextSb.Append("    , douji_irai_tousuu ")
            cmdTextSb.Append("    , tatemono_youto_mei ")
            cmdTextSb.Append("    , keiyu ")
            cmdTextSb.Append("    , koj_uri_syubetsu_mei ")
            cmdTextSb.Append("    , koj_support_system ")
            cmdTextSb.Append("    , kairy_koj_syubetu ")
            cmdTextSb.Append("    , siir_syouhin_mei1 ")
            cmdTextSb.Append("    , siir_syouhin_gaku1 ")
            cmdTextSb.Append("    , siir_syouhin_mei2 ")
            cmdTextSb.Append("    , siir_syouhin_gaku2 ")
            cmdTextSb.Append("    , siir_syouhin_mei3 ")
            cmdTextSb.Append("    , siir_syouhin_gaku3 ")
            cmdTextSb.Append("    , siir_syouhin_mei4 ")
            cmdTextSb.Append("    , siir_syouhin_gaku4 ")
            cmdTextSb.Append("    , siir_syouhin_mei5 ")
            cmdTextSb.Append("    , siir_syouhin_gaku5 ")
            cmdTextSb.Append("    , siir_syouhin_mei6 ")
            cmdTextSb.Append("    , siir_syouhin_gaku6 ")
            cmdTextSb.Append("    , saisin_hantei_naiyou ")
            cmdTextSb.Append("    , koj_hantei_flg ")
            cmdTextSb.Append("    , jiosaki_flg ")
            cmdTextSb.Append("    , hosyou_syouhin_umu ")
            cmdTextSb.Append("    , hosyousyo_hak_iraisyo_umu ")
            cmdTextSb.Append("    , hosyousyo_hak_iraisyo_tyk_date ")
            cmdTextSb.Append("    , hosyousyo_hak_jyky ")
            cmdTextSb.Append("    , hosyousyo_hak_date ")
            cmdTextSb.Append("    , hosyou_kaisi_date ")
            cmdTextSb.Append("    , data_haki_syubetu ")
            cmdTextSb.Append("    , send_sts ")
            cmdTextSb.Append("    , recv_sts ")
            cmdTextSb.Append("    , pdf_sts ")
            cmdTextSb.Append("    , earth_data_upd_datetime ")
            cmdTextSb.Append("    , earth_data_upd_login_user_id ")
            cmdTextSb.Append("    , mousikomi_no ")
            cmdTextSb.Append("    , yoteisyo_syudou_flg ")
            cmdTextSb.Append("    , bkn_adr3 ")
            cmdTextSb.Append("    , keiyaku_no ")
            cmdTextSb.Append("    , options ")
            cmdTextSb.Append("    , bukken_nayose_cd ")
            cmdTextSb.Append("    , siir_syouhin_cd1 ")
            cmdTextSb.Append("    , siir_syouhin_cd2 ")
            cmdTextSb.Append("    , siir_syouhin_cd3 ")
            cmdTextSb.Append("    , siir_syouhin_cd4 ")
            cmdTextSb.Append("    , siir_syouhin_cd5 ")
            cmdTextSb.Append("    , annaizu ")
            cmdTextSb.Append("    , haitizu ")
            cmdTextSb.Append("    , kakukai_heimenzu ")
            cmdTextSb.Append("    , ks_husezu ")
            cmdTextSb.Append("    , ks_danmenzu ")
            cmdTextSb.Append("    , zousei_keikakuzu ")
            cmdTextSb.Append("    , bukken_jyky_naiyou ")
            cmdTextSb.Append("    , kaiseki_kanry_naiyou ")
            cmdTextSb.Append("    , koj_kanry_handan ")
            cmdTextSb.Append("    , koj_kanry_naiyou ")
            cmdTextSb.Append("    , nyuukin_jyky_handan ")
            cmdTextSb.Append("    , nyuukin_jyky_naiyou ")
            cmdTextSb.Append("    , hak_irai_uke_datetime ")
            cmdTextSb.Append("    , hak_irai_can_datetime ")
            cmdTextSb.Append("    , hosyousyo_saihak_date ")
            cmdTextSb.Append("    , hosyou_kikan ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append(" SELECT ")
            cmdTextSb.Append("      TJ.kbn + TJ.hosyousyo_no ")
            cmdTextSb.Append("    , 0 ")
            cmdTextSb.Append("    , TJ.tys_gaiyou ")
            cmdTextSb.Append("    , MTH.tys_houhou_mei ")
            cmdTextSb.Append("    , MKZ.kouzou ")
            cmdTextSb.Append("    , TJ.sesyu_mei ")
            cmdTextSb.Append("    , TJ.bukken_jyuusyo1 ")
            cmdTextSb.Append("    , TJ.bukken_jyuusyo2 ")
            cmdTextSb.Append("    , TJ.tys_kibou_date ")
            cmdTextSb.Append("    , TJ.tys_kibou_jikan ")
            cmdTextSb.Append("    , TJ.irai_tantousya_mei ")
            cmdTextSb.Append("    , @CHOUSATACHIAI ")
            cmdTextSb.Append("    , TJ.kbn + TJ.kameiten_cd ")
            cmdTextSb.Append("    , MKM.kameiten_mei1 ")
            cmdTextSb.Append("    , MKJ.tel_no ")
            cmdTextSb.Append("    , MKJ.fax_no ")
            cmdTextSb.Append("    , MKJ.mail_address ")
            cmdTextSb.Append("    , TJ.tys_kaisya_cd ")
            cmdTextSb.Append("    , TJ.tys_kaisya_jigyousyo_cd ")
            cmdTextSb.Append("    , MTK.tys_kaisya_mei ")
            cmdTextSb.Append("    , TJ.tys_renrakusaki_atesaki_mei ")
            cmdTextSb.Append("    , TJ.tys_renrakusaki_tel ")
            cmdTextSb.Append("    , TJ.tys_renrakusaki_fax ")
            cmdTextSb.Append("    , TJ.tys_renrakusaki_mail ")
            cmdTextSb.Append("    , TJ.irai_tantousya_mei ")
            cmdTextSb.Append("    , MKM.tenmei_kana1 ")
            cmdTextSb.Append("    , MKZ.kouzou ")
            cmdTextSb.Append("    , MKS.kaisou ")
            cmdTextSb.Append("    , TJ.sekkei_kyoyou_sijiryoku ")
            cmdTextSb.Append("    , TJ.negiri_hukasa ")
            cmdTextSb.Append("    , MYK.yotei_ks_mei ")
            cmdTextSb.Append("    , MSY.syako ")
            cmdTextSb.Append("    , TJ.yotei_morituti_atusa ")
            cmdTextSb.Append("    , TJ.douji_irai_tousuu ")
            cmdTextSb.Append("    , MTY.tatemono_youto_mei ")
            cmdTextSb.Append("    , TJ.keiyu ")
            cmdTextSb.Append("    , MMSY.meisyou ")
            cmdTextSb.Append("    , MKM.koj_support_system ")
            cmdTextSb.Append("    , MKKS.kairy_koj_syubetu ")
            cmdTextSb.Append("    , syouhin.hinMei1 ")
            cmdTextSb.Append("    , syouhin.siireGaku1 ")
            cmdTextSb.Append("    , syouhin.hinMei2 ")
            cmdTextSb.Append("    , syouhin.siireGaku2 ")
            cmdTextSb.Append("    , syouhin.hinMei3 ")
            cmdTextSb.Append("    , syouhin.siireGaku3 ")
            cmdTextSb.Append("    , syouhin.hinMei4 ")
            cmdTextSb.Append("    , syouhin.siireGaku4 ")
            cmdTextSb.Append("    , syouhin.hinMei5 ")
            cmdTextSb.Append("    , syouhin.siireGaku5 ")
            cmdTextSb.Append("    , syouhin.hinMei6 ")
            cmdTextSb.Append("    , syouhin.siireGaku6 ")
            cmdTextSb.Append("    , MKSS.ks_siyou ")
            cmdTextSb.Append("    , TJ.koj_hantei_kekka_flg ")
            cmdTextSb.Append("    , MKM.jiosaki_flg ")
            cmdTextSb.Append("    , TJ.hosyou_syouhin_umu ")
            cmdTextSb.Append("    , TJ.hosyousyo_hak_iraisyo_umu ")
            cmdTextSb.Append("    , TJ.hosyousyo_hak_iraisyo_tyk_date ")
            cmdTextSb.Append("    , TJ.hosyousyo_hak_jyky ")
            cmdTextSb.Append("    , TJ.hosyousyo_hak_date ")
            cmdTextSb.Append("    , TJ.hosyou_kaisi_date ")
            cmdTextSb.Append("    , TJ.data_haki_syubetu ")
            cmdTextSb.Append("    , '00' ")
            cmdTextSb.Append("    , '00' ")
            cmdTextSb.Append("    , '00' ")
            cmdTextSb.Append("    , ISNULL ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      TJ.upd_datetime ")
            cmdTextSb.Append("    , TJ.add_datetime ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , ISNULL ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      TJ.upd_login_user_id ")
            cmdTextSb.Append("    , TJ.add_login_user_id ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , MI.mousikomi_no ")
            cmdTextSb.Append("    , TJ.yoyaku_zumi_flg ")
            cmdTextSb.Append("    , TJ.bukken_jyuusyo3 ")
            cmdTextSb.Append("    , TJ.keiyaku_no ")
            cmdTextSb.Append("    , @OPTIONS ")
            cmdTextSb.Append("    , TJ.bukken_nayose_cd ")
            cmdTextSb.Append("    , sc.scd1_1 ")
            cmdTextSb.Append("    , sc.scd2_1 ")
            cmdTextSb.Append("    , sc.scd2_2 ")
            cmdTextSb.Append("    , sc.scd2_3 ")
            cmdTextSb.Append("    , sc.scd2_4 ")
            cmdTextSb.Append("    , TJ.annaizu ")
            cmdTextSb.Append("    , TJ.haitizu ")
            cmdTextSb.Append("    , TJ.kakukai_heimenzu ")
            cmdTextSb.Append("    , TJ.ks_husezu ")
            cmdTextSb.Append("    , TJ.ks_danmenzu ")
            cmdTextSb.Append("    , TJ.zousei_keikakuzu ")
            cmdTextSb.Append("    , KM1.meisyou ")
            cmdTextSb.Append("    , KM2.meisyou ")
            cmdTextSb.Append("    , ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      CASE ")
            cmdTextSb.Append("           WHEN THK.koj_kanry = '0' ")
            cmdTextSb.Append("           THEN '－' ")
            cmdTextSb.Append("           WHEN THK.koj_kanry = '1' ")
            cmdTextSb.Append("           THEN '○' ")
            cmdTextSb.Append("           ELSE '×' ")
            cmdTextSb.Append("      END ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      CASE ")
            cmdTextSb.Append("           WHEN THK.koj_kanry = '0' ")
            cmdTextSb.Append("             OR THK.koj_kanry = '1' ")
            cmdTextSb.Append("           THEN NULL ")
            cmdTextSb.Append("           ELSE '工事実施の確認が取れておりません' ")
            cmdTextSb.Append("      END ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      CASE ")
            cmdTextSb.Append("           WHEN THK.nyuukin_jyky = '0' ")
            cmdTextSb.Append("           THEN '－' ")
            cmdTextSb.Append("           WHEN THK.nyuukin_jyky = '1' ")
            cmdTextSb.Append("             OR THK.nyuukin_jyky = '3' ")
            cmdTextSb.Append("             OR THK.nyuukin_jyky = '7' ")
            cmdTextSb.Append("           THEN '○' ")
            cmdTextSb.Append("           ELSE '×' ")
            cmdTextSb.Append("      END ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , ")
            cmdTextSb.Append(" ( ")
            cmdTextSb.Append("      CASE ")
            cmdTextSb.Append("           WHEN THK.nyuukin_jyky = '3' ")
            cmdTextSb.Append("           THEN '入金されなかった場合は無効となります' ")
            cmdTextSb.Append("           WHEN THK.nyuukin_jyky = '7' ")
            cmdTextSb.Append("           THEN '口座引落ができなかった場合は無効となります' ")
            cmdTextSb.Append("           WHEN THK.nyuukin_jyky = '2' ")
            cmdTextSb.Append("             OR THK.nyuukin_jyky = '4' ")
            cmdTextSb.Append("             OR THK.nyuukin_jyky = '5' ")
            cmdTextSb.Append("             OR THK.nyuukin_jyky = '6' ")
            cmdTextSb.Append("           THEN '御入金額が不足しています' ")
            cmdTextSb.Append("           ELSE NULL ")
            cmdTextSb.Append("      END ")
            cmdTextSb.Append(" ) ")
            cmdTextSb.Append("    , TJ.hak_irai_uke_datetime ")
            cmdTextSb.Append("    , TJ.hak_irai_can_datetime ")
            cmdTextSb.Append("    , TJ.hosyousyo_saihak_date ")
            cmdTextSb.Append("    , TJ.hosyou_kikan ")
            cmdTextSb.Append(" FROM ")
            cmdTextSb.Append("      t_jiban TJ ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tyousahouhou MTH ")
            cmdTextSb.Append("             ON TJ.tys_houhou = MTH.tys_houhou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kouzou MKZ ")
            cmdTextSb.Append("             ON TJ.kouzou = MKZ.kouzou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kameiten MKM ")
            cmdTextSb.Append("             ON TJ.kameiten_cd = MKM.kameiten_cd ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kameiten_jyuusyo MKJ ")
            cmdTextSb.Append("             ON TJ.kameiten_cd = MKJ.kameiten_cd ")
            cmdTextSb.Append("            AND 1 = MKJ.jyuusyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tyousakaisya MTK ")
            cmdTextSb.Append("             ON TJ.tys_kaisya_cd = MTK.tys_kaisya_cd ")
            cmdTextSb.Append("            AND TJ.tys_kaisya_jigyousyo_cd = MTK.jigyousyo_cd ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kaisou MKS ")
            cmdTextSb.Append("             ON TJ.kaisou = MKS.kaisou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_yotei_kiso MYK ")
            cmdTextSb.Append("             ON TJ.yotei_ks = MYK.yotei_ks_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_syako MSY ")
            cmdTextSb.Append("             ON TJ.syako = MSY.syako_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tatemono_youto MTY ")
            cmdTextSb.Append("             ON TJ.tatemono_youto_no = MTY.tatemono_youto_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_meisyou MMSY ")
            cmdTextSb.Append("             ON '55' = MMSY.meisyou_syubetu ")
            cmdTextSb.Append("            AND MKM.koj_uri_syubetsu = MMSY.code ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kairy_koj_syubetu MKKS ")
            cmdTextSb.Append("             ON TJ.kairy_koj_syubetu = MKKS.kairy_koj_syubetu_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN ")
            cmdTextSb.Append("               (SELECT ")
            cmdTextSb.Append("                     tjs.kbn ")
            cmdTextSb.Append("                   , tjs.hosyousyo_no ")
            cmdTextSb.Append("                   , s1.syouhin_mei hinMei1 ")
            cmdTextSb.Append("                   , s1.siire_gaku siireGaku1 ")
            cmdTextSb.Append("                   , s2.syouhin_mei hinMei2 ")
            cmdTextSb.Append("                   , s2.siire_gaku siireGaku2 ")
            cmdTextSb.Append("                   , s3.syouhin_mei hinMei3 ")
            cmdTextSb.Append("                   , s3.siire_gaku siireGaku3 ")
            cmdTextSb.Append("                   , s4.syouhin_mei hinMei4 ")
            cmdTextSb.Append("                   , s4.siire_gaku siireGaku4 ")
            cmdTextSb.Append("                   , s5.syouhin_mei hinMei5 ")
            cmdTextSb.Append("                   , s5.siire_gaku siireGaku5 ")
            cmdTextSb.Append("                   , s6.syouhin_mei hinMei6 ")
            cmdTextSb.Append("                   , s6.siire_gaku siireGaku6 ")
            cmdTextSb.Append("                FROM ")
            cmdTextSb.Append("                     jhs_sys.t_jiban tjs ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd = '100' ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s1 ")
            cmdTextSb.Append("                            ON tjs.kbn = s1.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s1.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s2 ")
            cmdTextSb.Append("                            ON tjs.kbn = s2.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s2.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 2 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s3 ")
            cmdTextSb.Append("                            ON tjs.kbn = s3.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s3.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 3 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s4 ")
            cmdTextSb.Append("                            ON tjs.kbn = s4.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s4.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 4 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s5 ")
            cmdTextSb.Append("                            ON tjs.kbn = s5.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s5.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , sum(t.siire_gaku) siire_gaku ")
            cmdTextSb.Append("                                  , 'その他' syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('120') ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                               GROUP BY ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s6 ")
            cmdTextSb.Append("                            ON tjs.kbn = s6.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s6.hosyousyo_no ")
            cmdTextSb.Append("               ) syouhin ")
            cmdTextSb.Append("             ON TJ.kbn = syouhin.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = syouhin.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN ")
            cmdTextSb.Append("               (SELECT ")
            cmdTextSb.Append("                     JBN.kbn ")
            cmdTextSb.Append("                   , JBN.hosyousyo_no ")
            cmdTextSb.Append("                   , SCD1.syouhin_cd scd1_1 ")
            cmdTextSb.Append("                   , SCD2.syouhin_cd scd2_1 ")
            cmdTextSb.Append("                   , SCD3.syouhin_cd scd2_2 ")
            cmdTextSb.Append("                   , SCD4.syouhin_cd scd2_3 ")
            cmdTextSb.Append("                   , SCD5.syouhin_cd scd2_4 ")
            cmdTextSb.Append("                FROM ")
            cmdTextSb.Append("                     jhs_sys.t_jiban JBN ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd = '100' ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD1 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD1.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD1.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD2 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD2.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD2.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 2 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD3 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD3.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD3.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 3 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD4 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD4.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD4.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 4 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD5 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD5.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD5.hosyousyo_no ")
            cmdTextSb.Append("               ) sc ")
            cmdTextSb.Append("             ON TJ.kbn = sc.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = sc.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_ks_siyou MKSS ")
            cmdTextSb.Append("             ON TJ.hantei_cd1 = MKSS.ks_siyou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN dbo.MousikomiIF MI ")
            cmdTextSb.Append("             ON TJ.kbn = MI.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = MI.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN t_hosyousyo_kanri THK ")
            cmdTextSb.Append("             ON TJ.kbn = THK.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = THK.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kakutyou_meisyou KM1 ")
            cmdTextSb.Append("             ON KM1.meisyou_syubetu = '10' ")
            cmdTextSb.Append("            AND THK.bukken_jyky = KM1.code ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kakutyou_meisyou KM2 ")
            cmdTextSb.Append("             ON KM2.meisyou_syubetu = '11' ")
            cmdTextSb.Append("            AND REPLACE(THK.kaiseki_kanry, '2', '0') = KM2.code ")
            cmdTextSb.Append(" WHERE ")
            cmdTextSb.Append("      TJ.kbn = @KBN ")
            cmdTextSb.Append("  AND TJ.hosyousyo_no = @NO ")
        Else '更新
            cmdTextSb.Append(" UPDATE ")
            cmdTextSb.Append("      dbo.ReportIF ")
            cmdTextSb.Append(" SET ")
            cmdTextSb.Append("      service_kbn = TJ.tys_gaiyou ")
            cmdTextSb.Append("    , tyousa = MTH.tys_houhou_mei ")
            cmdTextSb.Append("    , keikaku = MKZ.kouzou ")
            cmdTextSb.Append("    , sesyu_name = TJ.sesyu_mei ")
            cmdTextSb.Append("    , bkn_adr1 = TJ.bukken_jyuusyo1 ")
            cmdTextSb.Append("    , bkn_adr2 = TJ.bukken_jyuusyo2 ")
            cmdTextSb.Append("    , chousa_hope_date = TJ.tys_kibou_date ")
            cmdTextSb.Append("    , chousa_hope_time = TJ.tys_kibou_jikan ")
            cmdTextSb.Append("    , chousa_tanto = TJ.irai_tantousya_mei ")
            cmdTextSb.Append("    , chousa_tachiai = @CHOUSATACHIAI ")
            cmdTextSb.Append("    , kamei_cd = TJ.kbn + TJ.kameiten_cd ")
            cmdTextSb.Append("    , kamei_name = MKM.kameiten_mei1 ")
            cmdTextSb.Append("    , kamei_tel = MKJ.tel_no ")
            cmdTextSb.Append("    , kamei_fax = MKJ.fax_no ")
            cmdTextSb.Append("    , kamei_mail = MKJ.mail_address ")
            cmdTextSb.Append("    , tyousa_cd = TJ.tys_kaisya_cd ")
            cmdTextSb.Append("    , tyousa_brc = TJ.tys_kaisya_jigyousyo_cd ")
            cmdTextSb.Append("    , tyousa_name = MTK.tys_kaisya_mei ")
            cmdTextSb.Append("    , t_renraku_name = TJ.tys_renrakusaki_atesaki_mei ")
            cmdTextSb.Append("    , t_renraku_tel = TJ.tys_renrakusaki_tel ")
            cmdTextSb.Append("    , t_renraku_fax = TJ.tys_renrakusaki_fax ")
            cmdTextSb.Append("    , t_renraku_mail = TJ.tys_renrakusaki_mail ")
            cmdTextSb.Append("    , t_renraku_tanto = TJ.irai_tantousya_mei ")
            cmdTextSb.Append("    , tenmei_kana1 = MKM.tenmei_kana1 ")
            cmdTextSb.Append("    , kouzou = MKZ.kouzou ")
            cmdTextSb.Append("    , kaisou = MKS.kaisou ")
            cmdTextSb.Append("    , sekkei_kyoyou_sijiryoku = TJ.sekkei_kyoyou_sijiryoku ")
            cmdTextSb.Append("    , negiri_hukasa = TJ.negiri_hukasa ")
            cmdTextSb.Append("    , yotei_ks_mei = MYK.yotei_ks_mei ")
            cmdTextSb.Append("    , syako = MSY.syako ")
            cmdTextSb.Append("    , yotei_morituti_atusa = TJ.yotei_morituti_atusa ")
            cmdTextSb.Append("    , douji_irai_tousuu = TJ.douji_irai_tousuu ")
            cmdTextSb.Append("    , tatemono_youto_mei = MTY.tatemono_youto_mei ")
            cmdTextSb.Append("    , keiyu = TJ.keiyu ")
            cmdTextSb.Append("    , koj_uri_syubetsu_mei = MMSY.meisyou ")
            cmdTextSb.Append("    , koj_support_system = MKM.koj_support_system ")
            cmdTextSb.Append("    , kairy_koj_syubetu = MKKS.kairy_koj_syubetu ")
            cmdTextSb.Append("    , siir_syouhin_mei1 = syouhin.hinMei1 ")
            cmdTextSb.Append("    , siir_syouhin_gaku1 = syouhin.siireGaku1 ")
            cmdTextSb.Append("    , siir_syouhin_mei2 = syouhin.hinMei2 ")
            cmdTextSb.Append("    , siir_syouhin_gaku2 = syouhin.siireGaku2 ")
            cmdTextSb.Append("    , siir_syouhin_mei3 = syouhin.hinMei3 ")
            cmdTextSb.Append("    , siir_syouhin_gaku3 = syouhin.siireGaku3 ")
            cmdTextSb.Append("    , siir_syouhin_mei4 = syouhin.hinMei4 ")
            cmdTextSb.Append("    , siir_syouhin_gaku4 = syouhin.siireGaku4 ")
            cmdTextSb.Append("    , siir_syouhin_mei5 = syouhin.hinMei5 ")
            cmdTextSb.Append("    , siir_syouhin_gaku5 = syouhin.siireGaku5 ")
            cmdTextSb.Append("    , siir_syouhin_mei6 = syouhin.hinMei6 ")
            cmdTextSb.Append("    , siir_syouhin_gaku6 = syouhin.siireGaku6 ")
            cmdTextSb.Append("    , saisin_hantei_naiyou = MKSS.ks_siyou ")
            cmdTextSb.Append("    , koj_hantei_flg = TJ.koj_hantei_kekka_flg ")
            cmdTextSb.Append("    , jiosaki_flg = MKM.jiosaki_flg ")
            cmdTextSb.Append("    , hosyou_syouhin_umu = TJ.hosyou_syouhin_umu ")
            cmdTextSb.Append("    , hosyousyo_hak_iraisyo_umu = TJ.hosyousyo_hak_iraisyo_umu ")
            cmdTextSb.Append("    , hosyousyo_hak_iraisyo_tyk_date = TJ.hosyousyo_hak_iraisyo_tyk_date ")
            cmdTextSb.Append("    , hosyousyo_hak_jyky = TJ.hosyousyo_hak_jyky ")
            cmdTextSb.Append("    , hosyousyo_hak_date = TJ.hosyousyo_hak_date ")
            cmdTextSb.Append("    , hosyou_kaisi_date = TJ.hosyou_kaisi_date ")
            cmdTextSb.Append("    , data_haki_syubetu = TJ.data_haki_syubetu ")
            cmdTextSb.Append("    , send_sts = '00' ")
            cmdTextSb.Append("    , earth_data_upd_datetime = ISNULL(TJ.upd_datetime, TJ.add_datetime) ")
            cmdTextSb.Append("    , earth_data_upd_login_user_id = ISNULL(TJ.upd_login_user_id, TJ.add_login_user_id) ")
            cmdTextSb.Append("    , mousikomi_no = MI.mousikomi_no ")
            cmdTextSb.Append("    , yoteisyo_syudou_flg = TJ.yoyaku_zumi_flg ")
            cmdTextSb.Append("    , bkn_adr3 = TJ.bukken_jyuusyo3 ")
            cmdTextSb.Append("    , keiyaku_no = TJ.keiyaku_no")
            cmdTextSb.Append("    , options = @OPTIONS ")
            cmdTextSb.Append("    , bukken_nayose_cd = TJ.bukken_nayose_cd ")
            cmdTextSb.Append("    , siir_syouhin_cd1 = sc.scd1_1 ")
            cmdTextSb.Append("    , siir_syouhin_cd2 = sc.scd2_1 ")
            cmdTextSb.Append("    , siir_syouhin_cd3 = sc.scd2_2 ")
            cmdTextSb.Append("    , siir_syouhin_cd4 = sc.scd2_3 ")
            cmdTextSb.Append("    , siir_syouhin_cd5 = sc.scd2_4 ")
            cmdTextSb.Append("    , annaizu = TJ.annaizu ")
            cmdTextSb.Append("    , haitizu = TJ.haitizu ")
            cmdTextSb.Append("    , kakukai_heimenzu = TJ.kakukai_heimenzu ")
            cmdTextSb.Append("    , ks_husezu = TJ.ks_husezu ")
            cmdTextSb.Append("    , ks_danmenzu = TJ.ks_danmenzu ")
            cmdTextSb.Append("    , zousei_keikakuzu = TJ.zousei_keikakuzu ")
            cmdTextSb.Append("    , bukken_jyky_naiyou = KM1.meisyou ")
            cmdTextSb.Append("    , kaiseki_kanry_naiyou = KM2.meisyou ")
            cmdTextSb.Append("    , koj_kanry_handan =( ")
            cmdTextSb.Append("           CASE ")
            cmdTextSb.Append("                WHEN THK.koj_kanry = '0' ")
            cmdTextSb.Append("                THEN '－' ")
            cmdTextSb.Append("                WHEN THK.koj_kanry = '1' ")
            cmdTextSb.Append("                THEN '○' ")
            cmdTextSb.Append("                ELSE '×' ")
            cmdTextSb.Append("           END) ")
            cmdTextSb.Append("    , koj_kanry_naiyou =( ")
            cmdTextSb.Append("           CASE ")
            cmdTextSb.Append("                WHEN THK.koj_kanry = '0' ")
            cmdTextSb.Append("                  OR THK.koj_kanry = '1' ")
            cmdTextSb.Append("                THEN NULL ")
            cmdTextSb.Append("                ELSE '工事実施の確認が取れておりません' ")
            cmdTextSb.Append("           END) ")
            cmdTextSb.Append("    , nyuukin_jyky_handan =( ")
            cmdTextSb.Append("           CASE ")
            cmdTextSb.Append("                WHEN THK.nyuukin_jyky = '0' ")
            cmdTextSb.Append("                THEN '－' ")
            cmdTextSb.Append("                WHEN THK.nyuukin_jyky = '1' ")
            cmdTextSb.Append("                  OR THK.nyuukin_jyky = '3' ")
            cmdTextSb.Append("                  OR THK.nyuukin_jyky = '7' ")
            cmdTextSb.Append("                THEN '○' ")
            cmdTextSb.Append("                ELSE '×' ")
            cmdTextSb.Append("           END) ")
            cmdTextSb.Append("    , nyuukin_jyky_naiyou =( ")
            cmdTextSb.Append("           CASE ")
            cmdTextSb.Append("                WHEN THK.nyuukin_jyky = '3' ")
            cmdTextSb.Append("                THEN '入金されなかった場合は無効となります' ")
            cmdTextSb.Append("                WHEN THK.nyuukin_jyky = '7' ")
            cmdTextSb.Append("                THEN '口座引落ができなかった場合は無効となります' ")
            cmdTextSb.Append("                WHEN THK.nyuukin_jyky = '2' ")
            cmdTextSb.Append("                  OR THK.nyuukin_jyky = '4' ")
            cmdTextSb.Append("                  OR THK.nyuukin_jyky = '5' ")
            cmdTextSb.Append("                  OR THK.nyuukin_jyky = '6' ")
            cmdTextSb.Append("                THEN '御入金額が不足しています' ")
            cmdTextSb.Append("                ELSE NULL ")
            cmdTextSb.Append("           END) ")
            cmdTextSb.Append("    , hak_irai_uke_datetime = TJ.hak_irai_uke_datetime ")
            cmdTextSb.Append("    , hak_irai_can_datetime = TJ.hak_irai_can_datetime ")
            cmdTextSb.Append("    , hosyousyo_saihak_date = TJ.hosyousyo_saihak_date ")
            cmdTextSb.Append("    , hosyou_kikan          = TJ.hosyou_kikan ")
            cmdTextSb.Append(" FROM ")
            cmdTextSb.Append("      ReportIF RI ")
            cmdTextSb.Append("           LEFT OUTER JOIN t_jiban TJ ")
            cmdTextSb.Append("             ON @KBN = TJ.kbn ")
            cmdTextSb.Append("            AND @NO = TJ.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tyousahouhou MTH ")
            cmdTextSb.Append("             ON TJ.tys_houhou = MTH.tys_houhou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kouzou MKZ ")
            cmdTextSb.Append("             ON TJ.kouzou = MKZ.kouzou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kameiten MKM ")
            cmdTextSb.Append("             ON TJ.kameiten_cd = MKM.kameiten_cd ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kameiten_jyuusyo MKJ ")
            cmdTextSb.Append("             ON TJ.kameiten_cd = MKJ.kameiten_cd ")
            cmdTextSb.Append("            AND 1 = MKJ.jyuusyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tyousakaisya MTK ")
            cmdTextSb.Append("             ON TJ.tys_kaisya_cd = MTK.tys_kaisya_cd ")
            cmdTextSb.Append("            AND TJ.tys_kaisya_jigyousyo_cd = MTK.jigyousyo_cd ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kaisou MKS ")
            cmdTextSb.Append("             ON TJ.kaisou = MKS.kaisou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_yotei_kiso MYK ")
            cmdTextSb.Append("             ON TJ.yotei_ks = MYK.yotei_ks_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_syako MSY ")
            cmdTextSb.Append("             ON TJ.syako = MSY.syako_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_tatemono_youto MTY ")
            cmdTextSb.Append("             ON TJ.tatemono_youto_no = MTY.tatemono_youto_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_meisyou MMSY ")
            cmdTextSb.Append("             ON '55' = MMSY.meisyou_syubetu ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kairy_koj_syubetu MKKS ")
            cmdTextSb.Append("             ON TJ.kairy_koj_syubetu = MKKS.kairy_koj_syubetu_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN ")
            cmdTextSb.Append("               (SELECT ")
            cmdTextSb.Append("                     tjs.kbn ")
            cmdTextSb.Append("                   , tjs.hosyousyo_no ")
            cmdTextSb.Append("                   , s1.syouhin_mei hinMei1 ")
            cmdTextSb.Append("                   , s1.siire_gaku siireGaku1 ")
            cmdTextSb.Append("                   , s2.syouhin_mei hinMei2 ")
            cmdTextSb.Append("                   , s2.siire_gaku siireGaku2 ")
            cmdTextSb.Append("                   , s3.syouhin_mei hinMei3 ")
            cmdTextSb.Append("                   , s3.siire_gaku siireGaku3 ")
            cmdTextSb.Append("                   , s4.syouhin_mei hinMei4 ")
            cmdTextSb.Append("                   , s4.siire_gaku siireGaku4 ")
            cmdTextSb.Append("                   , s5.syouhin_mei hinMei5 ")
            cmdTextSb.Append("                   , s5.siire_gaku siireGaku5 ")
            cmdTextSb.Append("                   , s6.syouhin_mei hinMei6 ")
            cmdTextSb.Append("                   , s6.siire_gaku siireGaku6 ")
            cmdTextSb.Append("                FROM ")
            cmdTextSb.Append("                     jhs_sys.t_jiban tjs ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd = '100' ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s1 ")
            cmdTextSb.Append("                            ON tjs.kbn = s1.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s1.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s2 ")
            cmdTextSb.Append("                            ON tjs.kbn = s2.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s2.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 2 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s3 ")
            cmdTextSb.Append("                            ON tjs.kbn = s3.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s3.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 3 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s4 ")
            cmdTextSb.Append("                            ON tjs.kbn = s4.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s4.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.* ")
            cmdTextSb.Append("                                  , s.syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 4 ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s5 ")
            cmdTextSb.Append("                            ON tjs.kbn = s5.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s5.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , sum(t.siire_gaku) siire_gaku ")
            cmdTextSb.Append("                                  , 'その他' syouhin_mei ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.m_syouhin s ")
            cmdTextSb.Append("                                           ON t.syouhin_cd = s.syouhin_cd ")
            cmdTextSb.Append("                                          AND s.koj_type = 'RJ' ")
            cmdTextSb.Append("                                         INNER JOIN jhs_sys.t_jiban sub ")
            cmdTextSb.Append("                                           ON t.kbn = sub.kbn ")
            cmdTextSb.Append("                                          AND t.hosyousyo_no = sub.hosyousyo_no ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('120') ")
            cmdTextSb.Append("                                AND ((ISNULL(t.tys_kaisya_cd, '') = '' ")
            cmdTextSb.Append("                                AND ISNULL(t.tys_kaisya_jigyousyo_cd, '') = '') ")
            cmdTextSb.Append("                                 OR (t.tys_kaisya_cd = sub.tys_kaisya_cd ")
            cmdTextSb.Append("                                AND t.tys_kaisya_jigyousyo_cd = sub.tys_kaisya_jigyousyo_cd)) ")
            cmdTextSb.Append("                               GROUP BY ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               s6 ")
            cmdTextSb.Append("                            ON tjs.kbn = s6.kbn ")
            cmdTextSb.Append("                           AND tjs.hosyousyo_no = s6.hosyousyo_no ")
            cmdTextSb.Append("               ) syouhin ")
            cmdTextSb.Append("             ON TJ.kbn = syouhin.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = syouhin.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN ")
            cmdTextSb.Append("               (SELECT ")
            cmdTextSb.Append("                     JBN.kbn ")
            cmdTextSb.Append("                   , JBN.hosyousyo_no ")
            cmdTextSb.Append("                   , SCD1.syouhin_cd scd1_1 ")
            cmdTextSb.Append("                   , SCD2.syouhin_cd scd2_1 ")
            cmdTextSb.Append("                   , SCD3.syouhin_cd scd2_2 ")
            cmdTextSb.Append("                   , SCD4.syouhin_cd scd2_3 ")
            cmdTextSb.Append("                   , SCD5.syouhin_cd scd2_4 ")
            cmdTextSb.Append("                FROM ")
            cmdTextSb.Append("                     jhs_sys.t_jiban JBN ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd = '100' ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD1 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD1.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD1.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 1 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD2 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD2.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD2.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 2 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD3 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD3.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD3.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 3 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD4 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD4.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD4.hosyousyo_no ")
            cmdTextSb.Append("                          LEFT OUTER JOIN ")
            cmdTextSb.Append("                              (SELECT ")
            cmdTextSb.Append("                                    t.kbn ")
            cmdTextSb.Append("                                  , t.hosyousyo_no ")
            cmdTextSb.Append("                                  , t.syouhin_cd ")
            cmdTextSb.Append("                               FROM ")
            cmdTextSb.Append("                                    jhs_sys.t_teibetu_seikyuu t ")
            cmdTextSb.Append("                               WHERE ")
            cmdTextSb.Append("                                    t.bunrui_cd IN('110', '115') ")
            cmdTextSb.Append("                                AND t.gamen_hyouji_no = 4 ")
            cmdTextSb.Append("                              ) ")
            cmdTextSb.Append("                               SCD5 ")
            cmdTextSb.Append("                            ON JBN.kbn = SCD5.kbn ")
            cmdTextSb.Append("                           AND JBN.hosyousyo_no = SCD5.hosyousyo_no ")
            cmdTextSb.Append("               ) sc ")
            cmdTextSb.Append("             ON TJ.kbn = sc.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = sc.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_ks_siyou MKSS ")
            cmdTextSb.Append("             ON TJ.hantei_cd1 = MKSS.ks_siyou_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN dbo.MousikomiIF MI ")
            cmdTextSb.Append("             ON TJ.kbn = MI.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = MI.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN t_hosyousyo_kanri THK ")
            cmdTextSb.Append("             ON TJ.kbn = THK.kbn ")
            cmdTextSb.Append("            AND TJ.hosyousyo_no = THK.hosyousyo_no ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kakutyou_meisyou KM1 ")
            cmdTextSb.Append("             ON KM1.meisyou_syubetu = '10' ")
            cmdTextSb.Append("            AND THK.bukken_jyky = KM1.code ")
            cmdTextSb.Append("           LEFT OUTER JOIN m_kakutyou_meisyou KM2 ")
            cmdTextSb.Append("             ON KM2.meisyou_syubetu = '11' ")
            cmdTextSb.Append("            AND REPLACE(THK.kaiseki_kanry, '2', '0') = KM2.code ")
            cmdTextSb.Append(" WHERE ")
            cmdTextSb.Append("      RI.kokyaku_no = @KBN + @NO ")
            cmdTextSb.Append("  AND RI.kokyaku_brc = 0 ")

        End If

        ' クエリ実行
        intResult = ExecuteNonQuery(connStr, _
                                    CommandType.Text, _
                                    cmdTextSb.ToString, _
                                    cmdParams)

        Return intResult
    End Function

    ''' <summary>
    ''' 連携調査会社テーブルの存在チェックを行います
    ''' </summary>
    ''' <param name="tysKaisyaCd">調査会社コード</param>
    ''' <param name="jigyousyoCd">事業所コード</param>
    ''' <returns>存在する:True 存在しない:False</returns>
    ''' <remarks></remarks>
    Public Function ChkRenkeiTyousaKaisya(ByVal tysKaisyaCd As String, _
                                          ByVal jigyousyoCd As String) As Boolean

        'メソッド名、引数の情報の退避
        UnTrappedExceptionManager.AddMethodEntrance(ASSEMBLY_CLASSNAME & ".ChkRenkeiTyousaKaisya", _
                                                    tysKaisyaCd, _
                                                    jigyousyoCd)

        ' パラメータ
        Const strParamTysKaisyaCd As String = "@TYSKAISYA"
        Const strParamJigyousyoCd As String = "@JIGYOUSYO"

        Dim commandTextSb As New StringBuilder()

        commandTextSb.Append("SELECT  tys_kaisya_cd ")
        commandTextSb.Append("  FROM  m_renkei_tys_kaisya WITH (READCOMMITTED) ")
        commandTextSb.Append("  WHERE tys_kaisya_cd = " & strParamTysKaisyaCd)
        commandTextSb.Append("  AND   jigyousyo_cd = " & strParamJigyousyoCd)

        ' パラメータへ設定
        Dim commandParameters() As SqlParameter = _
            {SQLHelper.MakeParam(strParamTysKaisyaCd, SqlDbType.VarChar, 5, tysKaisyaCd), _
             SQLHelper.MakeParam(strParamJigyousyoCd, SqlDbType.VarChar, 2, jigyousyoCd)}

        ' データの取得
        Dim ReportIfDataSet As New ReportIfDataSet()

        ' 検索実行
        Dim ret As Object = SQLHelper.ExecuteScalar(connStr, _
                                CommandType.Text, _
                                commandTextSb.ToString(), _
                                commandParameters)

        ' 存在しない場合、Falseを返却
        If ret Is Nothing Then
            Return False
        End If

        Return True

    End Function

    ''' <summary>
    ''' 顧客番号を引数にデータを取得します
    ''' </summary>
    ''' <param name="kokyakuNo">顧客番号</param>
    ''' <returns>進捗データ用データテーブル</returns>
    ''' <remarks></remarks>
    Public Function GetReportIfData(ByVal kokyakuNo As String) As ReportIfDataSet.ReportIfTableDataTable

        'メソッド名、引数の情報の退避
        UnTrappedExceptionManager.AddMethodEntrance(ASSEMBLY_CLASSNAME & ".GetReportIfData", _
                                                    kokyakuNo)

        ' 戻り値
        'Dim strReportIfYm As String = ""

        ' パラメータ
        Const strParamKokyakuNo As String = "@KUBUN"

        Dim commandTextSb As New StringBuilder()

        commandTextSb.Append(" SELECT ")
        commandTextSb.Append("       kokyaku_no ")
        commandTextSb.Append("       , kokyaku_brc ")
        commandTextSb.Append("       , ISNULL(syouken_no,'') AS syouken_no ")
        commandTextSb.Append("       , kaiseki_kanry_naiyou ")
        commandTextSb.Append("       , koj_kanry_handan ")
        commandTextSb.Append("       , nyuukin_jyky_handan ")
        commandTextSb.Append("       , hak_irai_time ")
        commandTextSb.Append("       , koj_kanry_naiyou ")
        commandTextSb.Append("       , nyuukin_jyky_naiyou ")
        commandTextSb.Append("       , hosyousyo_hak_iraisyo_tyk_date ")
        commandTextSb.Append("       , hak_irai_time ")
        commandTextSb.Append("       , hak_irai_uke_datetime ")
        commandTextSb.Append("       , hak_irai_can_datetime ")
        commandTextSb.Append("       , hak_irai_bkn_name ")
        commandTextSb.Append("       , hak_irai_bkn_adr1 ")
        commandTextSb.Append("       , hak_irai_bkn_adr2 ")
        commandTextSb.Append("       , hak_irai_bkn_adr3 ")
        commandTextSb.Append("       , hak_irai_hw_date ")
        commandTextSb.Append("       , hak_irai_tanto ")
        commandTextSb.Append("       , hak_irai_tanto_tel ")
        commandTextSb.Append("       , hak_irai_login ")
        commandTextSb.Append("       , hak_irai_sonota ")
        commandTextSb.Append(" FROM ReportIF WITH (UPDLOCK) ")
        commandTextSb.Append(" WHERE kokyaku_no = " & strParamKokyakuNo)
        commandTextSb.Append(" AND kokyaku_brc  = 0 ")

        ' パラメータへ設定
        Dim commandParameters() As SqlParameter = _
            {SQLHelper.MakeParam(strParamKokyakuNo, SqlDbType.VarChar, 20, kokyakuNo)}

        ' データの取得
        Dim ReportIfDataSet As New ReportIfDataSet()

        ' 検索実行
        SQLHelper.FillDataset(connStr, CommandType.Text, commandTextSb.ToString(), _
            ReportIfDataSet, ReportIfDataSet.ReportIfTable.TableName, commandParameters)

        Dim reportIfTable As ReportIfDataSet.ReportIfTableDataTable = ReportIfDataSet.ReportIfTable

        Return reportIfTable

    End Function
End Class
